import { anyTag, type SheriffConfig, sameTag } from "@softarc/sheriff-core";

export const config: SheriffConfig = {
  entryPoints: {
    contracts: "./tools/sheriff-entry.ts",
    web: "./apps/web/src/router.tsx",
  },
  enableBarrelLess: true,
  encapsulationPattern: /(^|\/)internal(\/|$)/,
  modules: {
    "apps/web": "app:web",
    "apps/web/src/app/controller-session": "app:web:controller-session",
    "apps/web/src/app/local-state": "app:web:local-state",
    "apps/web/src/app/localization": "app:web:localization",
    "apps/web/src/app/providers": "app:web:providers",
    "apps/web/src/app/settings-options": "app:web:settings-options",
    "apps/web/src/app/theme": "app:web:theme",
    "apps/web/src/game-business/active-game": "app:web:active-game",
    "apps/web/src/game-business/installed-games/presentation.ts":
      "app:web:installed-game-presentation",
    "apps/web/src/game-business/installed-games": "app:web:installed-games",
    "apps/web/src/pages/app-shell": "app:web:page:app-shell",
    "apps/web/src/pages/catalog": "app:web:page:catalog",
    "apps/web/src/pages/combo-detail": "app:web:page:combo-detail",
    "apps/web/src/pages/custom-combo-builder": "app:web:page:custom-combo-builder",
    "apps/web/src/pages/first-launch": "app:web:page:first-launch",
    "apps/web/src/pages/named-lists": "app:web:page:named-lists",
    "apps/web/src/pages/route-recovery": "app:web:page:route-recovery",
    "apps/web/src/pages/shared-placeholder": "app:web:page-shared",
    "apps/web/src/routes": "app:web:routes",
    "apps/web/src/routing/web-path": "app:web:web-path",
    "packages/contracts": "pkg:contracts",
    "packages/builder-core": "pkg:builder-core",
    "packages/controller-bridge": "pkg:controller-bridge",
    "packages/ui": "pkg:ui",
    "mkxl/data": "mkxl:data",
    "mkxl/catalog": "mkxl:catalog",
    "mkxl/builder": "mkxl:builder",
    "mkxl/business": "mkxl:business",
    "mk1/data": "mk1:data",
    "mk1/catalog": "mk1:catalog",
    "mk1/builder": "mk1:builder",
    "mk1/business": "mk1:business",
  },
  depRules: {
    root: anyTag,
    noTag: anyTag,
    "app:web": [
      "app:web:routes",
      "app:web:web-path",
      "pkg:contracts",
      "pkg:builder-core",
      "pkg:controller-bridge",
      "pkg:ui",
    ],
    "app:web:controller-session": ["pkg:controller-bridge"],
    "app:web:local-state": ["app:web:installed-games", "pkg:contracts"],
    "app:web:localization": ["pkg:contracts"],
    "app:web:providers": [
      "app:web:controller-session",
      "app:web:local-state",
      "app:web:theme",
      "pkg:contracts",
      "pkg:ui",
    ],
    "app:web:settings-options": ["pkg:contracts", "pkg:ui"],
    "app:web:theme": ["pkg:contracts", "pkg:ui"],
    "app:web:active-game": ["app:web:installed-games", "pkg:contracts"],
    "app:web:installed-game-presentation": ["app:web:installed-games", "pkg:ui"],
    "app:web:installed-games": ["pkg:contracts", "mkxl:business", "mk1:business"],
    "app:web:page:*": [
      sameTag,
      "app:web:page-shared",
      "app:web:controller-session",
      "app:web:providers",
      "app:web:local-state",
      "app:web:localization",
      "app:web:settings-options",
      "app:web:active-game",
      "app:web:installed-game-presentation",
      "app:web:installed-games",
      "pkg:contracts",
      "pkg:builder-core",
      "pkg:controller-bridge",
      "pkg:ui",
    ],
    "app:web:page-shared": [
      "app:web:providers",
      "app:web:local-state",
      "app:web:active-game",
      "app:web:installed-games",
      "pkg:contracts",
      "pkg:builder-core",
      "pkg:controller-bridge",
      "pkg:ui",
    ],
    "app:web:routes": ["app:web:providers", "app:web:page:*"],
    "app:web:web-path": ["pkg:contracts"],
    "pkg:contracts": ["pkg:contracts"],
    "pkg:builder-core": ["pkg:builder-core", "pkg:contracts"],
    "pkg:controller-bridge": ["pkg:controller-bridge", "pkg:contracts"],
    "pkg:ui": ["pkg:ui", "pkg:contracts"],
    "mkxl:data": ["mkxl:data", "pkg:contracts"],
    "mkxl:catalog": ["mkxl:catalog", "mkxl:data", "pkg:contracts"],
    "mkxl:builder": [
      "mkxl:builder",
      "mkxl:catalog",
      "mkxl:data",
      "pkg:builder-core",
      "pkg:contracts",
    ],
    "mkxl:business": [
      "mkxl:business",
      "mkxl:builder",
      "mkxl:catalog",
      "mkxl:data",
      "pkg:builder-core",
      "pkg:contracts",
    ],
    "mk1:data": ["mk1:data", "pkg:contracts"],
    "mk1:catalog": ["mk1:catalog", "mk1:data", "pkg:contracts"],
    "mk1:builder": ["mk1:builder", "mk1:catalog", "mk1:data", "pkg:builder-core", "pkg:contracts"],
    "mk1:business": [
      "mk1:business",
      "mk1:builder",
      "mk1:catalog",
      "mk1:data",
      "pkg:builder-core",
      "pkg:contracts",
    ],
  },
};
