import { anyTag, type SheriffConfig } from "@softarc/sheriff-core";

export const config: SheriffConfig = {
  entryFile: "./tools/sheriff-entry.ts",
  enableBarrelLess: true,
  modules: {
    "apps/web": "app:web",
    "packages/contracts": "pkg:contracts",
    "packages/builder-core": "pkg:builder-core",
    "packages/controller-bridge": "pkg:controller-bridge",
    "packages/ui": "pkg:ui",
    "mkxl/data": "mkxl:data",
    "mkxl/rules": "mkxl:rules",
    "mkxl/catalog": "mkxl:catalog",
    "mkxl/builder": "mkxl:builder",
    "mkxl/business": "mkxl:business",
    "mk1/data": "mk1:data",
    "mk1/rules": "mk1:rules",
    "mk1/catalog": "mk1:catalog",
    "mk1/builder": "mk1:builder",
    "mk1/business": "mk1:business",
  },
  depRules: {
    root: anyTag,
    noTag: anyTag,
    "app:web": [
      "app:web",
      "pkg:contracts",
      "pkg:builder-core",
      "pkg:controller-bridge",
      "pkg:ui",
      "mkxl:business",
      "mk1:business",
    ],
    "pkg:contracts": ["pkg:contracts"],
    "pkg:builder-core": ["pkg:builder-core", "pkg:contracts"],
    "pkg:controller-bridge": ["pkg:controller-bridge", "pkg:contracts"],
    "pkg:ui": ["pkg:ui", "pkg:contracts"],
    "mkxl:data": ["mkxl:data", "pkg:contracts"],
    "mkxl:rules": ["mkxl:rules", "mkxl:data", "pkg:contracts"],
    "mkxl:catalog": ["mkxl:catalog", "mkxl:rules", "mkxl:data", "pkg:contracts"],
    "mkxl:builder": [
      "mkxl:builder",
      "mkxl:catalog",
      "mkxl:rules",
      "mkxl:data",
      "pkg:builder-core",
      "pkg:contracts",
    ],
    "mkxl:business": [
      "mkxl:business",
      "mkxl:builder",
      "mkxl:catalog",
      "mkxl:rules",
      "mkxl:data",
      "pkg:builder-core",
      "pkg:contracts",
    ],
    "mk1:data": ["mk1:data", "pkg:contracts"],
    "mk1:rules": ["mk1:rules", "mk1:data", "pkg:contracts"],
    "mk1:catalog": ["mk1:catalog", "mk1:rules", "mk1:data", "pkg:contracts"],
    "mk1:builder": [
      "mk1:builder",
      "mk1:catalog",
      "mk1:rules",
      "mk1:data",
      "pkg:builder-core",
      "pkg:contracts",
    ],
    "mk1:business": [
      "mk1:business",
      "mk1:builder",
      "mk1:catalog",
      "mk1:rules",
      "mk1:data",
      "pkg:builder-core",
      "pkg:contracts",
    ],
  },
};
