import type { NotationDisplayMode } from "@mk-combos/contracts/settings/type";
import { notationDisplayModes } from "@mk-combos/contracts/settings/value";

export { notationDisplayModes };

const uiNotationControllerControlTokens = {
  dpadDown: "dpadDown",
  dpadLeft: "dpadLeft",
  dpadRight: "dpadRight",
  dpadUp: "dpadUp",
  faceEast: "faceEast",
  faceNorth: "faceNorth",
  faceSouth: "faceSouth",
  faceWest: "faceWest",
  home: "home",
  leftShoulder: "leftShoulder",
  leftStickDown: "leftStickDown",
  leftStickLeft: "leftStickLeft",
  leftStickPress: "leftStickPress",
  leftStickRight: "leftStickRight",
  leftStickUp: "leftStickUp",
  leftTrigger: "leftTrigger",
  rightShoulder: "rightShoulder",
  rightStickDown: "rightStickDown",
  rightStickLeft: "rightStickLeft",
  rightStickPress: "rightStickPress",
  rightStickRight: "rightStickRight",
  rightStickUp: "rightStickUp",
  rightTrigger: "rightTrigger",
  select: "select",
  start: "start",
} as const;

export const uiNotationIconKinds = {
  attack: "attack",
  control: "control",
  direction: "direction",
  displayMode: "displayMode",
  frameWindow: "frameWindow",
  modifier: "modifier",
  separator: "separator",
  state: "state",
} as const;

export const uiNotationTokens = {
  "1": "1",
  "2": "2",
  "3": "3",
  "4": "4",
  AMP: "AMP",
  B: "B",
  BLK: "BLK",
  D: "D",
  F: "F",
  INT: "INT",
  K: "K",
  SS: "SS",
  U: "U",
  ...uiNotationControllerControlTokens,
} as const;

type UiNotationTokenValue = (typeof uiNotationTokens)[keyof typeof uiNotationTokens];
type UiNotationIconKindValue = (typeof uiNotationIconKinds)[keyof typeof uiNotationIconKinds];

export const uiNotationTokenStates = {
  disabled: "disabled",
  focused: "focused",
  highlighted: "highlighted",
  invalid: "invalid",
  ready: "ready",
  stale: "stale",
  unavailable: "unavailable",
} as const;

export const uiNotationDisplayModeIconNames = {
  FGC: "notation-display-fgc",
  PlayStation: "notation-display-playstation",
  Xbox: "notation-display-xbox",
} as const satisfies Record<NotationDisplayMode, string>;

export const uiNotationTokenKinds = {
  "1": "attack",
  "2": "attack",
  "3": "attack",
  "4": "attack",
  K: "attack",
  BLK: "modifier",
  SS: "modifier",
  INT: "modifier",
  AMP: "modifier",
  U: "direction",
  D: "direction",
  B: "direction",
  F: "direction",
  faceSouth: "control",
  faceEast: "control",
  faceWest: "control",
  faceNorth: "control",
  leftShoulder: "control",
  rightShoulder: "control",
  leftTrigger: "control",
  rightTrigger: "control",
  select: "control",
  start: "control",
  leftStickPress: "control",
  rightStickPress: "control",
  dpadUp: "direction",
  dpadDown: "direction",
  dpadLeft: "direction",
  dpadRight: "direction",
  home: "control",
  leftStickLeft: "direction",
  leftStickRight: "direction",
  leftStickUp: "direction",
  leftStickDown: "direction",
  rightStickLeft: "direction",
  rightStickRight: "direction",
  rightStickUp: "direction",
  rightStickDown: "direction",
} as const satisfies Record<UiNotationTokenValue, UiNotationIconKindValue>;

export const uiNotationModeTokenLabels = {
  FGC: {
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    AMP: "AMP",
    B: "B",
    BLK: "BLK",
    D: "D",
    F: "F",
    INT: "INT",
    K: "K",
    SS: "SS",
    U: "U",
    dpadDown: "D-pad down",
    dpadLeft: "D-pad left",
    dpadRight: "D-pad right",
    dpadUp: "D-pad up",
    faceEast: "Face east",
    faceNorth: "Face north",
    faceSouth: "Face south",
    faceWest: "Face west",
    home: "Home",
    leftShoulder: "Left shoulder",
    leftStickDown: "Left stick down",
    leftStickLeft: "Left stick left",
    leftStickPress: "Left stick press",
    leftStickRight: "Left stick right",
    leftStickUp: "Left stick up",
    leftTrigger: "Left trigger",
    rightShoulder: "Right shoulder",
    rightStickDown: "Right stick down",
    rightStickLeft: "Right stick left",
    rightStickPress: "Right stick press",
    rightStickRight: "Right stick right",
    rightStickUp: "Right stick up",
    rightTrigger: "Right trigger",
    select: "Select",
    start: "Start",
  },
  PlayStation: {
    "1": "Square",
    "2": "Triangle",
    "3": "Cross",
    "4": "Circle",
    AMP: "AMP",
    B: "Back",
    BLK: "Block",
    D: "Down",
    F: "Forward",
    INT: "Interact",
    K: "Kameo",
    SS: "Stance switch",
    U: "Up",
    dpadDown: "D-pad down",
    dpadLeft: "D-pad left",
    dpadRight: "D-pad right",
    dpadUp: "D-pad up",
    faceEast: "Circle",
    faceNorth: "Triangle",
    faceSouth: "Cross",
    faceWest: "Square",
    home: "PS",
    leftShoulder: "L1",
    leftStickDown: "Left stick down",
    leftStickLeft: "Left stick left",
    leftStickPress: "L3",
    leftStickRight: "Left stick right",
    leftStickUp: "Left stick up",
    leftTrigger: "L2",
    rightShoulder: "R1",
    rightStickDown: "Right stick down",
    rightStickLeft: "Right stick left",
    rightStickPress: "R3",
    rightStickRight: "Right stick right",
    rightStickUp: "Right stick up",
    rightTrigger: "R2",
    select: "Create",
    start: "Options",
  },
  Xbox: {
    "1": "X",
    "2": "Y",
    "3": "A",
    "4": "B",
    AMP: "AMP",
    B: "Back",
    BLK: "Block",
    D: "Down",
    F: "Forward",
    INT: "Interact",
    K: "Kameo",
    SS: "Stance switch",
    U: "Up",
    dpadDown: "D-pad down",
    dpadLeft: "D-pad left",
    dpadRight: "D-pad right",
    dpadUp: "D-pad up",
    faceEast: "B",
    faceNorth: "Y",
    faceSouth: "A",
    faceWest: "X",
    home: "Guide",
    leftShoulder: "LB",
    leftStickDown: "Left stick down",
    leftStickLeft: "Left stick left",
    leftStickPress: "LS",
    leftStickRight: "Left stick right",
    leftStickUp: "Left stick up",
    leftTrigger: "LT",
    rightShoulder: "RB",
    rightStickDown: "Right stick down",
    rightStickLeft: "Right stick left",
    rightStickPress: "RS",
    rightStickRight: "Right stick right",
    rightStickUp: "Right stick up",
    rightTrigger: "RT",
    select: "View",
    start: "Menu",
  },
} as const satisfies Record<NotationDisplayMode, Record<UiNotationTokenValue, string>>;

export const uiNotationModeTokenIconNames = {
  FGC: {
    "1": "notation-fgc-1",
    "2": "notation-fgc-2",
    "3": "notation-fgc-3",
    "4": "notation-fgc-4",
    AMP: "notation-amplify",
    B: "notation-back",
    BLK: "notation-block",
    D: "notation-down",
    F: "notation-forward",
    INT: "notation-interactable",
    K: "notation-kameo",
    SS: "notation-stance-switch",
    U: "notation-up",
    dpadDown: "notation-control-dpad-down",
    dpadLeft: "notation-control-dpad-left",
    dpadRight: "notation-control-dpad-right",
    dpadUp: "notation-control-dpad-up",
    faceEast: "notation-control-face-east",
    faceNorth: "notation-control-face-north",
    faceSouth: "notation-control-face-south",
    faceWest: "notation-control-face-west",
    home: "notation-control-home",
    leftShoulder: "notation-control-left-shoulder",
    leftStickDown: "notation-control-left-stick-down",
    leftStickLeft: "notation-control-left-stick-left",
    leftStickPress: "notation-control-left-stick-press",
    leftStickRight: "notation-control-left-stick-right",
    leftStickUp: "notation-control-left-stick-up",
    leftTrigger: "notation-control-left-trigger",
    rightShoulder: "notation-control-right-shoulder",
    rightStickDown: "notation-control-right-stick-down",
    rightStickLeft: "notation-control-right-stick-left",
    rightStickPress: "notation-control-right-stick-press",
    rightStickRight: "notation-control-right-stick-right",
    rightStickUp: "notation-control-right-stick-up",
    rightTrigger: "notation-control-right-trigger",
    select: "notation-control-select",
    start: "notation-control-start",
  },
  PlayStation: {
    "1": "notation-playstation-square",
    "2": "notation-playstation-triangle",
    "3": "notation-playstation-cross",
    "4": "notation-playstation-circle",
    AMP: "notation-amplify",
    B: "notation-back",
    BLK: "notation-block",
    D: "notation-down",
    F: "notation-forward",
    INT: "notation-interactable",
    K: "notation-kameo",
    SS: "notation-stance-switch",
    U: "notation-up",
    dpadDown: "notation-playstation-dpad-down",
    dpadLeft: "notation-playstation-dpad-left",
    dpadRight: "notation-playstation-dpad-right",
    dpadUp: "notation-playstation-dpad-up",
    faceEast: "notation-playstation-circle",
    faceNorth: "notation-playstation-triangle",
    faceSouth: "notation-playstation-cross",
    faceWest: "notation-playstation-square",
    home: "notation-playstation-ps",
    leftShoulder: "notation-playstation-l1",
    leftStickDown: "notation-playstation-left-stick-down",
    leftStickLeft: "notation-playstation-left-stick-left",
    leftStickPress: "notation-playstation-l3",
    leftStickRight: "notation-playstation-left-stick-right",
    leftStickUp: "notation-playstation-left-stick-up",
    leftTrigger: "notation-playstation-l2",
    rightShoulder: "notation-playstation-r1",
    rightStickDown: "notation-playstation-right-stick-down",
    rightStickLeft: "notation-playstation-right-stick-left",
    rightStickPress: "notation-playstation-r3",
    rightStickRight: "notation-playstation-right-stick-right",
    rightStickUp: "notation-playstation-right-stick-up",
    rightTrigger: "notation-playstation-r2",
    select: "notation-playstation-create",
    start: "notation-playstation-options",
  },
  Xbox: {
    "1": "notation-xbox-x",
    "2": "notation-xbox-y",
    "3": "notation-xbox-a",
    "4": "notation-xbox-b",
    AMP: "notation-amplify",
    B: "notation-back",
    BLK: "notation-block",
    D: "notation-down",
    F: "notation-forward",
    INT: "notation-interactable",
    K: "notation-kameo",
    SS: "notation-stance-switch",
    U: "notation-up",
    dpadDown: "notation-xbox-dpad-down",
    dpadLeft: "notation-xbox-dpad-left",
    dpadRight: "notation-xbox-dpad-right",
    dpadUp: "notation-xbox-dpad-up",
    faceEast: "notation-xbox-b",
    faceNorth: "notation-xbox-y",
    faceSouth: "notation-xbox-a",
    faceWest: "notation-xbox-x",
    home: "notation-xbox-guide",
    leftShoulder: "notation-xbox-lb",
    leftStickDown: "notation-xbox-left-stick-down",
    leftStickLeft: "notation-xbox-left-stick-left",
    leftStickPress: "notation-xbox-ls",
    leftStickRight: "notation-xbox-left-stick-right",
    leftStickUp: "notation-xbox-left-stick-up",
    leftTrigger: "notation-xbox-lt",
    rightShoulder: "notation-xbox-rb",
    rightStickDown: "notation-xbox-right-stick-down",
    rightStickLeft: "notation-xbox-right-stick-left",
    rightStickPress: "notation-xbox-rs",
    rightStickRight: "notation-xbox-right-stick-right",
    rightStickUp: "notation-xbox-right-stick-up",
    rightTrigger: "notation-xbox-rt",
    select: "notation-xbox-view",
    start: "notation-xbox-menu",
  },
} as const satisfies Record<NotationDisplayMode, Record<UiNotationTokenValue, string>>;
