import type { GameIconAsset } from "../type";
import { gameIconKinds } from "../value";

export const mkxlCharacterIcons = [
  {
    accessibleLabel: "Alien character",
    assetPath: "icons/game/mkxl/characters/alien.svg",
    gameId: "mkxl",
    id: "alien",
    kind: gameIconKinds.character,
    src: new URL("./characters/alien.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Bo' Rai Cho character",
    assetPath: "icons/game/mkxl/characters/bo-rai-cho.svg",
    gameId: "mkxl",
    id: "bo-rai-cho",
    kind: gameIconKinds.character,
    src: new URL("./characters/bo-rai-cho.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Cassie Cage character",
    assetPath: "icons/game/mkxl/characters/cassie-cage.svg",
    gameId: "mkxl",
    id: "cassie-cage",
    kind: gameIconKinds.character,
    src: new URL("./characters/cassie-cage.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "D'Vorah character",
    assetPath: "icons/game/mkxl/characters/dvorah.svg",
    gameId: "mkxl",
    id: "dvorah",
    kind: gameIconKinds.character,
    src: new URL("./characters/dvorah.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ermac character",
    assetPath: "icons/game/mkxl/characters/ermac.svg",
    gameId: "mkxl",
    id: "ermac",
    kind: gameIconKinds.character,
    src: new URL("./characters/ermac.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Erron Black character",
    assetPath: "icons/game/mkxl/characters/erron-black.svg",
    gameId: "mkxl",
    id: "erron-black",
    kind: gameIconKinds.character,
    src: new URL("./characters/erron-black.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ferra/Torr character",
    assetPath: "icons/game/mkxl/characters/ferra-torr.svg",
    gameId: "mkxl",
    id: "ferra-torr",
    kind: gameIconKinds.character,
    src: new URL("./characters/ferra-torr.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Goro character",
    assetPath: "icons/game/mkxl/characters/goro.svg",
    gameId: "mkxl",
    id: "goro",
    kind: gameIconKinds.character,
    src: new URL("./characters/goro.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Jacqui Briggs character",
    assetPath: "icons/game/mkxl/characters/jacqui-briggs.svg",
    gameId: "mkxl",
    id: "jacqui-briggs",
    kind: gameIconKinds.character,
    src: new URL("./characters/jacqui-briggs.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Jason Voorhees character",
    assetPath: "icons/game/mkxl/characters/jason-voorhees.svg",
    gameId: "mkxl",
    id: "jason-voorhees",
    kind: gameIconKinds.character,
    src: new URL("./characters/jason-voorhees.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Jax character",
    assetPath: "icons/game/mkxl/characters/jax.svg",
    gameId: "mkxl",
    id: "jax",
    kind: gameIconKinds.character,
    src: new URL("./characters/jax.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Johnny Cage character",
    assetPath: "icons/game/mkxl/characters/johnny-cage.svg",
    gameId: "mkxl",
    id: "johnny-cage",
    kind: gameIconKinds.character,
    src: new URL("./characters/johnny-cage.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kano character",
    assetPath: "icons/game/mkxl/characters/kano.svg",
    gameId: "mkxl",
    id: "kano",
    kind: gameIconKinds.character,
    src: new URL("./characters/kano.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kenshi character",
    assetPath: "icons/game/mkxl/characters/kenshi.svg",
    gameId: "mkxl",
    id: "kenshi",
    kind: gameIconKinds.character,
    src: new URL("./characters/kenshi.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kitana character",
    assetPath: "icons/game/mkxl/characters/kitana.svg",
    gameId: "mkxl",
    id: "kitana",
    kind: gameIconKinds.character,
    src: new URL("./characters/kitana.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kotal Kahn character",
    assetPath: "icons/game/mkxl/characters/kotal-kahn.svg",
    gameId: "mkxl",
    id: "kotal-kahn",
    kind: gameIconKinds.character,
    src: new URL("./characters/kotal-kahn.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kung Jin character",
    assetPath: "icons/game/mkxl/characters/kung-jin.svg",
    gameId: "mkxl",
    id: "kung-jin",
    kind: gameIconKinds.character,
    src: new URL("./characters/kung-jin.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kung Lao character",
    assetPath: "icons/game/mkxl/characters/kung-lao.svg",
    gameId: "mkxl",
    id: "kung-lao",
    kind: gameIconKinds.character,
    src: new URL("./characters/kung-lao.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Leatherface character",
    assetPath: "icons/game/mkxl/characters/leatherface.svg",
    gameId: "mkxl",
    id: "leatherface",
    kind: gameIconKinds.character,
    src: new URL("./characters/leatherface.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Liu Kang character",
    assetPath: "icons/game/mkxl/characters/liu-kang.svg",
    gameId: "mkxl",
    id: "liu-kang",
    kind: gameIconKinds.character,
    src: new URL("./characters/liu-kang.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Mileena character",
    assetPath: "icons/game/mkxl/characters/mileena.svg",
    gameId: "mkxl",
    id: "mileena",
    kind: gameIconKinds.character,
    src: new URL("./characters/mileena.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Predator character",
    assetPath: "icons/game/mkxl/characters/predator.svg",
    gameId: "mkxl",
    id: "predator",
    kind: gameIconKinds.character,
    src: new URL("./characters/predator.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Quan Chi character",
    assetPath: "icons/game/mkxl/characters/quan-chi.svg",
    gameId: "mkxl",
    id: "quan-chi",
    kind: gameIconKinds.character,
    src: new URL("./characters/quan-chi.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Raiden character",
    assetPath: "icons/game/mkxl/characters/raiden.svg",
    gameId: "mkxl",
    id: "raiden",
    kind: gameIconKinds.character,
    src: new URL("./characters/raiden.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Reptile character",
    assetPath: "icons/game/mkxl/characters/reptile.svg",
    gameId: "mkxl",
    id: "reptile",
    kind: gameIconKinds.character,
    src: new URL("./characters/reptile.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Scorpion character",
    assetPath: "icons/game/mkxl/characters/scorpion.svg",
    gameId: "mkxl",
    id: "scorpion",
    kind: gameIconKinds.character,
    src: new URL("./characters/scorpion.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Shinnok character",
    assetPath: "icons/game/mkxl/characters/shinnok.svg",
    gameId: "mkxl",
    id: "shinnok",
    kind: gameIconKinds.character,
    src: new URL("./characters/shinnok.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Sonya Blade character",
    assetPath: "icons/game/mkxl/characters/sonya-blade.svg",
    gameId: "mkxl",
    id: "sonya-blade",
    kind: gameIconKinds.character,
    src: new URL("./characters/sonya-blade.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Sub-Zero character",
    assetPath: "icons/game/mkxl/characters/sub-zero.svg",
    gameId: "mkxl",
    id: "sub-zero",
    kind: gameIconKinds.character,
    src: new URL("./characters/sub-zero.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Takeda character",
    assetPath: "icons/game/mkxl/characters/takeda.svg",
    gameId: "mkxl",
    id: "takeda",
    kind: gameIconKinds.character,
    src: new URL("./characters/takeda.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Tanya character",
    assetPath: "icons/game/mkxl/characters/tanya.svg",
    gameId: "mkxl",
    id: "tanya",
    kind: gameIconKinds.character,
    src: new URL("./characters/tanya.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Tremor character",
    assetPath: "icons/game/mkxl/characters/tremor.svg",
    gameId: "mkxl",
    id: "tremor",
    kind: gameIconKinds.character,
    src: new URL("./characters/tremor.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Triborg character",
    assetPath: "icons/game/mkxl/characters/triborg.svg",
    gameId: "mkxl",
    id: "triborg",
    kind: gameIconKinds.character,
    src: new URL("./characters/triborg.svg", import.meta.url).href,
  },
] as const satisfies readonly GameIconAsset[];
