import type { GameIconAsset } from "../type";
import { gameIconKinds } from "../value";

export const mkxlInteractableIcons = [
  {
    accessibleLabel: "Body Toss interactable",
    assetPath: "icons/game/mkxl/interactables/crossroads/body-toss.svg",
    gameId: "mkxl",
    id: "crossroads:body-toss",
    kind: gameIconKinds.interactable,
    parentId: "crossroads",
    src: new URL("./interactables/crossroads/body-toss.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ram Skull interactable",
    assetPath: "icons/game/mkxl/interactables/crossroads/ram-skull.svg",
    gameId: "mkxl",
    id: "crossroads:ram-skull",
    kind: gameIconKinds.interactable,
    parentId: "crossroads",
    src: new URL("./interactables/crossroads/ram-skull.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Rock Jump interactable",
    assetPath: "icons/game/mkxl/interactables/crossroads/rock-jump.svg",
    gameId: "mkxl",
    id: "crossroads:rock-jump",
    kind: gameIconKinds.interactable,
    parentId: "crossroads",
    src: new URL("./interactables/crossroads/rock-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Wall Dive interactable",
    assetPath: "icons/game/mkxl/interactables/crossroads/wall-dive.svg",
    gameId: "mkxl",
    id: "crossroads:wall-dive",
    kind: gameIconKinds.interactable,
    parentId: "crossroads",
    src: new URL("./interactables/crossroads/wall-dive.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Branch Strike interactable",
    assetPath: "icons/game/mkxl/interactables/dead-woods/branch-strike.svg",
    gameId: "mkxl",
    id: "dead-woods:branch-strike",
    kind: gameIconKinds.interactable,
    parentId: "dead-woods",
    src: new URL("./interactables/dead-woods/branch-strike.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Tree Jump interactable",
    assetPath: "icons/game/mkxl/interactables/dead-woods/tree-jump.svg",
    gameId: "mkxl",
    id: "dead-woods:tree-jump",
    kind: gameIconKinds.interactable,
    parentId: "dead-woods",
    src: new URL("./interactables/dead-woods/tree-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Stump Jump interactable",
    assetPath: "icons/game/mkxl/interactables/dead-woods/stump-jump.svg",
    gameId: "mkxl",
    id: "dead-woods:stump-jump",
    kind: gameIconKinds.interactable,
    parentId: "dead-woods",
    src: new URL("./interactables/dead-woods/stump-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Tree Swing interactable",
    assetPath: "icons/game/mkxl/interactables/dead-woods/tree-swing.svg",
    gameId: "mkxl",
    id: "dead-woods:tree-swing",
    kind: gameIconKinds.interactable,
    parentId: "dead-woods",
    src: new URL("./interactables/dead-woods/tree-swing.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Throwable Log interactable",
    assetPath: "icons/game/mkxl/interactables/dead-woods/throwable-log.svg",
    gameId: "mkxl",
    id: "dead-woods:throwable-log",
    kind: gameIconKinds.interactable,
    parentId: "dead-woods",
    src: new URL("./interactables/dead-woods/throwable-log.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Engine interactable",
    assetPath: "icons/game/mkxl/interactables/destroyed-city/engine.svg",
    gameId: "mkxl",
    id: "destroyed-city:engine",
    kind: gameIconKinds.interactable,
    parentId: "destroyed-city",
    src: new URL("./interactables/destroyed-city/engine.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Traffic Light interactable",
    assetPath: "icons/game/mkxl/interactables/destroyed-city/traffic-light.svg",
    gameId: "mkxl",
    id: "destroyed-city:traffic-light",
    kind: gameIconKinds.interactable,
    parentId: "destroyed-city",
    src: new URL("./interactables/destroyed-city/traffic-light.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Car Jump interactable",
    assetPath: "icons/game/mkxl/interactables/destroyed-city/car-jump.svg",
    gameId: "mkxl",
    id: "destroyed-city:car-jump",
    kind: gameIconKinds.interactable,
    parentId: "destroyed-city",
    src: new URL("./interactables/destroyed-city/car-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Exhaust Pipe interactable",
    assetPath: "icons/game/mkxl/interactables/destroyed-city/exhaust-pipe.svg",
    gameId: "mkxl",
    id: "destroyed-city:exhaust-pipe",
    kind: gameIconKinds.interactable,
    parentId: "destroyed-city",
    src: new URL("./interactables/destroyed-city/exhaust-pipe.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Wooden Plank interactable",
    assetPath: "icons/game/mkxl/interactables/emperors-courtyard/wooden-plank.svg",
    gameId: "mkxl",
    id: "emperors-courtyard:wooden-plank",
    kind: gameIconKinds.interactable,
    parentId: "emperors-courtyard",
    src: new URL("./interactables/emperors-courtyard/wooden-plank.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Left Pillar Jump interactable",
    assetPath: "icons/game/mkxl/interactables/emperors-courtyard/left-pillar-jump.svg",
    gameId: "mkxl",
    id: "emperors-courtyard:left-pillar-jump",
    kind: gameIconKinds.interactable,
    parentId: "emperors-courtyard",
    src: new URL("./interactables/emperors-courtyard/left-pillar-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Shield interactable",
    assetPath: "icons/game/mkxl/interactables/emperors-courtyard/shield.svg",
    gameId: "mkxl",
    id: "emperors-courtyard:shield",
    kind: gameIconKinds.interactable,
    parentId: "emperors-courtyard",
    src: new URL("./interactables/emperors-courtyard/shield.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Brick Pile Jump interactable",
    assetPath: "icons/game/mkxl/interactables/emperors-courtyard/brick-pile-jump.svg",
    gameId: "mkxl",
    id: "emperors-courtyard:brick-pile-jump",
    kind: gameIconKinds.interactable,
    parentId: "emperors-courtyard",
    src: new URL("./interactables/emperors-courtyard/brick-pile-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Right Pillar Grab interactable",
    assetPath: "icons/game/mkxl/interactables/emperors-courtyard/right-pillar-grab.svg",
    gameId: "mkxl",
    id: "emperors-courtyard:right-pillar-grab",
    kind: gameIconKinds.interactable,
    parentId: "emperors-courtyard",
    src: new URL("./interactables/emperors-courtyard/right-pillar-grab.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Molten Coals interactable",
    assetPath: "icons/game/mkxl/interactables/emperors-courtyard/molten-coals.svg",
    gameId: "mkxl",
    id: "emperors-courtyard:molten-coals",
    kind: gameIconKinds.interactable,
    parentId: "emperors-courtyard",
    src: new URL("./interactables/emperors-courtyard/molten-coals.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Jinsei Grab interactable",
    assetPath: "icons/game/mkxl/interactables/jinsei-chamber/jinsei-grab.svg",
    gameId: "mkxl",
    id: "jinsei-chamber:jinsei-grab",
    kind: gameIconKinds.interactable,
    parentId: "jinsei-chamber",
    src: new URL("./interactables/jinsei-chamber/jinsei-grab.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Cauldron interactable",
    assetPath: "icons/game/mkxl/interactables/jinsei-chamber/cauldron.svg",
    gameId: "mkxl",
    id: "jinsei-chamber:cauldron",
    kind: gameIconKinds.interactable,
    parentId: "jinsei-chamber",
    src: new URL("./interactables/jinsei-chamber/cauldron.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Corner Wall Dive interactable",
    assetPath: "icons/game/mkxl/interactables/jinsei-chamber/corner-wall-dive.svg",
    gameId: "mkxl",
    id: "jinsei-chamber:corner-wall-dive",
    kind: gameIconKinds.interactable,
    parentId: "jinsei-chamber",
    src: new URL("./interactables/jinsei-chamber/corner-wall-dive.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Corner Wall Dive interactable",
    assetPath: "icons/game/mkxl/interactables/kuatan-jungle/corner-wall-dive.svg",
    gameId: "mkxl",
    id: "kuatan-jungle:corner-wall-dive",
    kind: gameIconKinds.interactable,
    parentId: "kuatan-jungle",
    src: new URL("./interactables/kuatan-jungle/corner-wall-dive.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Vine Swing interactable",
    assetPath: "icons/game/mkxl/interactables/kuatan-jungle/vine-swing.svg",
    gameId: "mkxl",
    id: "kuatan-jungle:vine-swing",
    kind: gameIconKinds.interactable,
    parentId: "kuatan-jungle",
    src: new URL("./interactables/kuatan-jungle/vine-swing.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Statue Grab Jump interactable",
    assetPath: "icons/game/mkxl/interactables/kuatan-jungle/statue-grab-jump.svg",
    gameId: "mkxl",
    id: "kuatan-jungle:statue-grab-jump",
    kind: gameIconKinds.interactable,
    parentId: "kuatan-jungle",
    src: new URL("./interactables/kuatan-jungle/statue-grab-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Hanging Vine interactable",
    assetPath: "icons/game/mkxl/interactables/kuatan-jungle/hanging-vine.svg",
    gameId: "mkxl",
    id: "kuatan-jungle:hanging-vine",
    kind: gameIconKinds.interactable,
    parentId: "kuatan-jungle",
    src: new URL("./interactables/kuatan-jungle/hanging-vine.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Dragon Statue Jump interactable",
    assetPath: "icons/game/mkxl/interactables/lin-kuei-temple/dragon-statue-jump.svg",
    gameId: "mkxl",
    id: "lin-kuei-temple:dragon-statue-jump",
    kind: gameIconKinds.interactable,
    parentId: "lin-kuei-temple",
    src: new URL("./interactables/lin-kuei-temple/dragon-statue-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Small Flame interactable",
    assetPath: "icons/game/mkxl/interactables/lin-kuei-temple/small-flame.svg",
    gameId: "mkxl",
    id: "lin-kuei-temple:small-flame",
    kind: gameIconKinds.interactable,
    parentId: "lin-kuei-temple",
    src: new URL("./interactables/lin-kuei-temple/small-flame.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Coffin Jump interactable",
    assetPath: "icons/game/mkxl/interactables/lin-kuei-temple/coffin-jump.svg",
    gameId: "mkxl",
    id: "lin-kuei-temple:coffin-jump",
    kind: gameIconKinds.interactable,
    parentId: "lin-kuei-temple",
    src: new URL("./interactables/lin-kuei-temple/coffin-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Statue Flame interactable",
    assetPath: "icons/game/mkxl/interactables/lin-kuei-temple/statue-flame.svg",
    gameId: "mkxl",
    id: "lin-kuei-temple:statue-flame",
    kind: gameIconKinds.interactable,
    parentId: "lin-kuei-temple",
    src: new URL("./interactables/lin-kuei-temple/statue-flame.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Tree Wall Dive interactable",
    assetPath: "icons/game/mkxl/interactables/lin-kuei-temple/tree-wall-dive.svg",
    gameId: "mkxl",
    id: "lin-kuei-temple:tree-wall-dive",
    kind: gameIconKinds.interactable,
    parentId: "lin-kuei-temple",
    src: new URL("./interactables/lin-kuei-temple/tree-wall-dive.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Lava Bowl interactable",
    assetPath: "icons/game/mkxl/interactables/outworld-marketplace/lava-bowl.svg",
    gameId: "mkxl",
    id: "outworld-marketplace:lava-bowl",
    kind: gameIconKinds.interactable,
    parentId: "outworld-marketplace",
    src: new URL("./interactables/outworld-marketplace/lava-bowl.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Fruit Barrel interactable",
    assetPath: "icons/game/mkxl/interactables/outworld-marketplace/fruit-barrel.svg",
    gameId: "mkxl",
    id: "outworld-marketplace:fruit-barrel",
    kind: gameIconKinds.interactable,
    parentId: "outworld-marketplace",
    src: new URL("./interactables/outworld-marketplace/fruit-barrel.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Beast Jump interactable",
    assetPath: "icons/game/mkxl/interactables/outworld-marketplace/beast-jump.svg",
    gameId: "mkxl",
    id: "outworld-marketplace:beast-jump",
    kind: gameIconKinds.interactable,
    parentId: "outworld-marketplace",
    src: new URL("./interactables/outworld-marketplace/beast-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Blanche interactable",
    assetPath: "icons/game/mkxl/interactables/outworld-marketplace/blanche.svg",
    gameId: "mkxl",
    id: "outworld-marketplace:blanche",
    kind: gameIconKinds.interactable,
    parentId: "outworld-marketplace",
    src: new URL("./interactables/outworld-marketplace/blanche.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Tarp Jump interactable",
    assetPath: "icons/game/mkxl/interactables/outworld-marketplace/tarp-jump.svg",
    gameId: "mkxl",
    id: "outworld-marketplace:tarp-jump",
    kind: gameIconKinds.interactable,
    parentId: "outworld-marketplace",
    src: new URL("./interactables/outworld-marketplace/tarp-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Torch Stick interactable",
    assetPath: "icons/game/mkxl/interactables/quan-chi-fortress/torch-stick.svg",
    gameId: "mkxl",
    id: "quan-chi-fortress:torch-stick",
    kind: gameIconKinds.interactable,
    parentId: "quan-chi-fortress",
    src: new URL("./interactables/quan-chi-fortress/torch-stick.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Orb Lantern interactable",
    assetPath: "icons/game/mkxl/interactables/quan-chi-fortress/orb-lantern.svg",
    gameId: "mkxl",
    id: "quan-chi-fortress:orb-lantern",
    kind: gameIconKinds.interactable,
    parentId: "quan-chi-fortress",
    src: new URL("./interactables/quan-chi-fortress/orb-lantern.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Lantern and Chest Jump interactable",
    assetPath: "icons/game/mkxl/interactables/quan-chi-fortress/lantern-chest-jump.svg",
    gameId: "mkxl",
    id: "quan-chi-fortress:lantern-chest-jump",
    kind: gameIconKinds.interactable,
    parentId: "quan-chi-fortress",
    src: new URL("./interactables/quan-chi-fortress/lantern-chest-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Demon Jar interactable",
    assetPath: "icons/game/mkxl/interactables/quan-chi-fortress/demon-jar.svg",
    gameId: "mkxl",
    id: "quan-chi-fortress:demon-jar",
    kind: gameIconKinds.interactable,
    parentId: "quan-chi-fortress",
    src: new URL("./interactables/quan-chi-fortress/demon-jar.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Shao Kahn's Hammer interactable",
    assetPath: "icons/game/mkxl/interactables/quan-chi-fortress/shaokahn-hammer.svg",
    gameId: "mkxl",
    id: "quan-chi-fortress:shaokahn-hammer",
    kind: gameIconKinds.interactable,
    parentId: "quan-chi-fortress",
    src: new URL("./interactables/quan-chi-fortress/shaokahn-hammer.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Spiked War Club interactable",
    assetPath: "icons/game/mkxl/interactables/refugee-kamp/spiked-war-club.svg",
    gameId: "mkxl",
    id: "refugee-kamp:spiked-war-club",
    kind: gameIconKinds.interactable,
    parentId: "refugee-kamp",
    src: new URL("./interactables/refugee-kamp/spiked-war-club.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ladder Jump interactable",
    assetPath: "icons/game/mkxl/interactables/refugee-kamp/ladder-jump.svg",
    gameId: "mkxl",
    id: "refugee-kamp:ladder-jump",
    kind: gameIconKinds.interactable,
    parentId: "refugee-kamp",
    src: new URL("./interactables/refugee-kamp/ladder-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "ATV Jump interactable",
    assetPath: "icons/game/mkxl/interactables/refugee-kamp/atv-jump.svg",
    gameId: "mkxl",
    id: "refugee-kamp:atv-jump",
    kind: gameIconKinds.interactable,
    parentId: "refugee-kamp",
    src: new URL("./interactables/refugee-kamp/atv-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Burning Can interactable",
    assetPath: "icons/game/mkxl/interactables/refugee-kamp/burning-can.svg",
    gameId: "mkxl",
    id: "refugee-kamp:burning-can",
    kind: gameIconKinds.interactable,
    parentId: "refugee-kamp",
    src: new URL("./interactables/refugee-kamp/burning-can.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Wall Dive interactable",
    assetPath: "icons/game/mkxl/interactables/refugee-kamp/wall-dive.svg",
    gameId: "mkxl",
    id: "refugee-kamp:wall-dive",
    kind: gameIconKinds.interactable,
    parentId: "refugee-kamp",
    src: new URL("./interactables/refugee-kamp/wall-dive.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Burning Pyre interactable",
    assetPath: "icons/game/mkxl/interactables/sky-temple/burning-pyre.svg",
    gameId: "mkxl",
    id: "sky-temple:burning-pyre",
    kind: gameIconKinds.interactable,
    parentId: "sky-temple",
    src: new URL("./interactables/sky-temple/burning-pyre.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Monk interactable",
    assetPath: "icons/game/mkxl/interactables/sky-temple/monk.svg",
    gameId: "mkxl",
    id: "sky-temple:monk",
    kind: gameIconKinds.interactable,
    parentId: "sky-temple",
    src: new URL("./interactables/sky-temple/monk.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Gong Wall Dive interactable",
    assetPath: "icons/game/mkxl/interactables/sky-temple/gong-wall-dive.svg",
    gameId: "mkxl",
    id: "sky-temple:gong-wall-dive",
    kind: gameIconKinds.interactable,
    parentId: "sky-temple",
    src: new URL("./interactables/sky-temple/gong-wall-dive.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Lantern interactable",
    assetPath: "icons/game/mkxl/interactables/sky-temple/lantern.svg",
    gameId: "mkxl",
    id: "sky-temple:lantern",
    kind: gameIconKinds.interactable,
    parentId: "sky-temple",
    src: new URL("./interactables/sky-temple/lantern.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ship Wall Dive interactable",
    assetPath: "icons/game/mkxl/interactables/the-kove/ship-wall-dive.svg",
    gameId: "mkxl",
    id: "the-kove:ship-wall-dive",
    kind: gameIconKinds.interactable,
    parentId: "the-kove",
    src: new URL("./interactables/the-kove/ship-wall-dive.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Box interactable",
    assetPath: "icons/game/mkxl/interactables/the-kove/box.svg",
    gameId: "mkxl",
    id: "the-kove:box",
    kind: gameIconKinds.interactable,
    parentId: "the-kove",
    src: new URL("./interactables/the-kove/box.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Pier Jump interactable",
    assetPath: "icons/game/mkxl/interactables/the-kove/pier-jump.svg",
    gameId: "mkxl",
    id: "the-kove:pier-jump",
    kind: gameIconKinds.interactable,
    parentId: "the-kove",
    src: new URL("./interactables/the-kove/pier-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Corpse interactable",
    assetPath: "icons/game/mkxl/interactables/the-kove/corpse.svg",
    gameId: "mkxl",
    id: "the-kove:corpse",
    kind: gameIconKinds.interactable,
    parentId: "the-kove",
    src: new URL("./interactables/the-kove/corpse.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Pot interactable",
    assetPath: "icons/game/mkxl/interactables/the-kove/pot.svg",
    gameId: "mkxl",
    id: "the-kove:pot",
    kind: gameIconKinds.interactable,
    parentId: "the-kove",
    src: new URL("./interactables/the-kove/pot.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Hook Swing interactable",
    assetPath: "icons/game/mkxl/interactables/the-kove/hook-swing.svg",
    gameId: "mkxl",
    id: "the-kove:hook-swing",
    kind: gameIconKinds.interactable,
    parentId: "the-kove",
    src: new URL("./interactables/the-kove/hook-swing.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Corner Dive Kick interactable",
    assetPath: "icons/game/mkxl/interactables/the-pit/corner-dive-kick.svg",
    gameId: "mkxl",
    id: "the-pit:corner-dive-kick",
    kind: gameIconKinds.interactable,
    parentId: "the-pit",
    src: new URL("./interactables/the-pit/corner-dive-kick.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Lantern interactable",
    assetPath: "icons/game/mkxl/interactables/the-pit/lantern.svg",
    gameId: "mkxl",
    id: "the-pit:lantern",
    kind: gameIconKinds.interactable,
    parentId: "the-pit",
    src: new URL("./interactables/the-pit/lantern.svg", import.meta.url).href,
  },
] as const satisfies readonly GameIconAsset[];
