import type { GameIconAsset } from "../type";
import { gameIconKinds } from "../value";

export const mkxlStateIcons = [
  {
    accessibleLabel: "Random Character",
    assetPath: "icons/game/mkxl/shared/states/random-character.svg",
    gameId: "mkxl",
    id: "states:random-character",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/random-character.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "No Variation",
    assetPath: "icons/game/mkxl/shared/states/no-variation.svg",
    gameId: "mkxl",
    id: "states:no-variation",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/no-variation.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Hidden Variation",
    assetPath: "icons/game/mkxl/shared/states/hidden-variation.svg",
    gameId: "mkxl",
    id: "states:hidden-variation",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/hidden-variation.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "DLC",
    assetPath: "icons/game/mkxl/shared/states/dlc.svg",
    gameId: "mkxl",
    id: "states:dlc",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/dlc.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Guest",
    assetPath: "icons/game/mkxl/shared/states/guest.svg",
    gameId: "mkxl",
    id: "states:guest",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/guest.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Boss",
    assetPath: "icons/game/mkxl/shared/states/boss.svg",
    gameId: "mkxl",
    id: "states:boss",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/boss.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Hidden",
    assetPath: "icons/game/mkxl/shared/states/hidden.svg",
    gameId: "mkxl",
    id: "states:hidden",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/hidden.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Completed",
    assetPath: "icons/game/mkxl/shared/states/completed.svg",
    gameId: "mkxl",
    id: "states:completed",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/completed.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Favorite",
    assetPath: "icons/game/mkxl/shared/states/favorite.svg",
    gameId: "mkxl",
    id: "states:favorite",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/favorite.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Missing Asset",
    assetPath: "icons/game/mkxl/shared/states/missing-asset.svg",
    gameId: "mkxl",
    id: "states:missing-asset",
    kind: gameIconKinds.state,
    src: new URL("./shared/states/missing-asset.svg", import.meta.url).href,
  },
] as const satisfies readonly GameIconAsset[];

export const mkxlInteractableTypeIcons = [
  {
    accessibleLabel: "Throwable",
    assetPath: "icons/game/mkxl/shared/interactable-types/throwable.svg",
    gameId: "mkxl",
    id: "interactable-types:throwable",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/throwable.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Heavy Throwable",
    assetPath: "icons/game/mkxl/shared/interactable-types/heavy-throwable.svg",
    gameId: "mkxl",
    id: "interactable-types:heavy-throwable",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/heavy-throwable.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Melee Strike",
    assetPath: "icons/game/mkxl/shared/interactable-types/melee-strike.svg",
    gameId: "mkxl",
    id: "interactable-types:melee-strike",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/melee-strike.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Low Strike",
    assetPath: "icons/game/mkxl/shared/interactable-types/low-strike.svg",
    gameId: "mkxl",
    id: "interactable-types:low-strike",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/low-strike.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Overhead Strike",
    assetPath: "icons/game/mkxl/shared/interactable-types/overhead-strike.svg",
    gameId: "mkxl",
    id: "interactable-types:overhead-strike",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/overhead-strike.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Wall Jump",
    assetPath: "icons/game/mkxl/shared/interactable-types/wall-jump.svg",
    gameId: "mkxl",
    id: "interactable-types:wall-jump",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/wall-jump.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Dive Kick",
    assetPath: "icons/game/mkxl/shared/interactable-types/dive-kick.svg",
    gameId: "mkxl",
    id: "interactable-types:dive-kick",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/dive-kick.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Swing",
    assetPath: "icons/game/mkxl/shared/interactable-types/swing.svg",
    gameId: "mkxl",
    id: "interactable-types:swing",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/swing.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Grab",
    assetPath: "icons/game/mkxl/shared/interactable-types/grab.svg",
    gameId: "mkxl",
    id: "interactable-types:grab",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/grab.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Multi-hit",
    assetPath: "icons/game/mkxl/shared/interactable-types/multi-hit.svg",
    gameId: "mkxl",
    id: "interactable-types:multi-hit",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/multi-hit.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Escape",
    assetPath: "icons/game/mkxl/shared/interactable-types/escape.svg",
    gameId: "mkxl",
    id: "interactable-types:escape",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/escape.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Stage Brutality",
    assetPath: "icons/game/mkxl/shared/interactable-types/stage-brutality.svg",
    gameId: "mkxl",
    id: "interactable-types:stage-brutality",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/stage-brutality.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Stage Fatality",
    assetPath: "icons/game/mkxl/shared/interactable-types/stage-fatality.svg",
    gameId: "mkxl",
    id: "interactable-types:stage-fatality",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/stage-fatality.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Alternative Action",
    assetPath: "icons/game/mkxl/shared/interactable-types/alternative-action.svg",
    gameId: "mkxl",
    id: "interactable-types:alternative-action",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/alternative-action.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Character-specific Action",
    assetPath: "icons/game/mkxl/shared/interactable-types/character-specific-action.svg",
    gameId: "mkxl",
    id: "interactable-types:character-specific-action",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/character-specific-action.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Consumable",
    assetPath: "icons/game/mkxl/shared/interactable-types/consumable.svg",
    gameId: "mkxl",
    id: "interactable-types:consumable",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/consumable.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Reusable",
    assetPath: "icons/game/mkxl/shared/interactable-types/reusable.svg",
    gameId: "mkxl",
    id: "interactable-types:reusable",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/reusable.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Left Side",
    assetPath: "icons/game/mkxl/shared/interactable-types/left-side.svg",
    gameId: "mkxl",
    id: "interactable-types:left-side",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/left-side.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Center",
    assetPath: "icons/game/mkxl/shared/interactable-types/center.svg",
    gameId: "mkxl",
    id: "interactable-types:center",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/center.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Right Side",
    assetPath: "icons/game/mkxl/shared/interactable-types/right-side.svg",
    gameId: "mkxl",
    id: "interactable-types:right-side",
    kind: gameIconKinds["interactable-type"],
    src: new URL("./shared/interactable-types/right-side.svg", import.meta.url).href,
  },
] as const satisfies readonly GameIconAsset[];

export const mkxlRealmIcons = [
  {
    accessibleLabel: "Earthrealm",
    assetPath: "icons/game/mkxl/shared/realms/earthrealm.svg",
    gameId: "mkxl",
    id: "realms:earthrealm",
    kind: gameIconKinds.realm,
    src: new URL("./shared/realms/earthrealm.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Outworld",
    assetPath: "icons/game/mkxl/shared/realms/outworld.svg",
    gameId: "mkxl",
    id: "realms:outworld",
    kind: gameIconKinds.realm,
    src: new URL("./shared/realms/outworld.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Netherrealm",
    assetPath: "icons/game/mkxl/shared/realms/netherrealm.svg",
    gameId: "mkxl",
    id: "realms:netherrealm",
    kind: gameIconKinds.realm,
    src: new URL("./shared/realms/netherrealm.svg", import.meta.url).href,
  },
] as const satisfies readonly GameIconAsset[];

export const mkxlFactionIcons = [
  {
    accessibleLabel: "Black Dragon",
    assetPath: "icons/game/mkxl/shared/factions/black-dragon.svg",
    gameId: "mkxl",
    id: "factions:black-dragon",
    kind: gameIconKinds.faction,
    src: new URL("./shared/factions/black-dragon.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Brotherhood of Shadow",
    assetPath: "icons/game/mkxl/shared/factions/brotherhood-of-shadow.svg",
    gameId: "mkxl",
    id: "factions:brotherhood-of-shadow",
    kind: gameIconKinds.faction,
    src: new URL("./shared/factions/brotherhood-of-shadow.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Lin Kuei",
    assetPath: "icons/game/mkxl/shared/factions/lin-kuei.svg",
    gameId: "mkxl",
    id: "factions:lin-kuei",
    kind: gameIconKinds.faction,
    src: new URL("./shared/factions/lin-kuei.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Special Forces",
    assetPath: "icons/game/mkxl/shared/factions/special-forces.svg",
    gameId: "mkxl",
    id: "factions:special-forces",
    kind: gameIconKinds.faction,
    src: new URL("./shared/factions/special-forces.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "White Lotus",
    assetPath: "icons/game/mkxl/shared/factions/white-lotus.svg",
    gameId: "mkxl",
    id: "factions:white-lotus",
    kind: gameIconKinds.faction,
    src: new URL("./shared/factions/white-lotus.svg", import.meta.url).href,
  },
] as const satisfies readonly GameIconAsset[];

export const mkxlSharedIcons = [
  ...mkxlStateIcons,
  ...mkxlInteractableTypeIcons,
  ...mkxlRealmIcons,
  ...mkxlFactionIcons,
] as const satisfies readonly GameIconAsset[];
