import type { GameIconAsset } from "../type";
import { gameIconKinds } from "../value";

export const mkxlStageIcons = [
  {
    accessibleLabel: "Crossroads stage",
    assetPath: "icons/game/mkxl/stages/crossroads.svg",
    gameId: "mkxl",
    id: "crossroads",
    kind: gameIconKinds.stage,
    src: new URL("./stages/crossroads.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Dead Woods stage",
    assetPath: "icons/game/mkxl/stages/dead-woods.svg",
    gameId: "mkxl",
    id: "dead-woods",
    kind: gameIconKinds.stage,
    src: new URL("./stages/dead-woods.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Destroyed City stage",
    assetPath: "icons/game/mkxl/stages/destroyed-city.svg",
    gameId: "mkxl",
    id: "destroyed-city",
    kind: gameIconKinds.stage,
    src: new URL("./stages/destroyed-city.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Emperor's Courtyard stage",
    assetPath: "icons/game/mkxl/stages/emperors-courtyard.svg",
    gameId: "mkxl",
    id: "emperors-courtyard",
    kind: gameIconKinds.stage,
    src: new URL("./stages/emperors-courtyard.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Jinsei Chamber stage",
    assetPath: "icons/game/mkxl/stages/jinsei-chamber.svg",
    gameId: "mkxl",
    id: "jinsei-chamber",
    kind: gameIconKinds.stage,
    src: new URL("./stages/jinsei-chamber.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kuatan Jungle stage",
    assetPath: "icons/game/mkxl/stages/kuatan-jungle.svg",
    gameId: "mkxl",
    id: "kuatan-jungle",
    kind: gameIconKinds.stage,
    src: new URL("./stages/kuatan-jungle.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Lin Kuei Temple stage",
    assetPath: "icons/game/mkxl/stages/lin-kuei-temple.svg",
    gameId: "mkxl",
    id: "lin-kuei-temple",
    kind: gameIconKinds.stage,
    src: new URL("./stages/lin-kuei-temple.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Outworld Marketplace stage",
    assetPath: "icons/game/mkxl/stages/outworld-marketplace.svg",
    gameId: "mkxl",
    id: "outworld-marketplace",
    kind: gameIconKinds.stage,
    src: new URL("./stages/outworld-marketplace.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Quan Chi Fortress stage",
    assetPath: "icons/game/mkxl/stages/quan-chi-fortress.svg",
    gameId: "mkxl",
    id: "quan-chi-fortress",
    kind: gameIconKinds.stage,
    src: new URL("./stages/quan-chi-fortress.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Refugee Kamp stage",
    assetPath: "icons/game/mkxl/stages/refugee-kamp.svg",
    gameId: "mkxl",
    id: "refugee-kamp",
    kind: gameIconKinds.stage,
    src: new URL("./stages/refugee-kamp.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Sky Temple stage",
    assetPath: "icons/game/mkxl/stages/sky-temple.svg",
    gameId: "mkxl",
    id: "sky-temple",
    kind: gameIconKinds.stage,
    src: new URL("./stages/sky-temple.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "The Kove stage",
    assetPath: "icons/game/mkxl/stages/the-kove.svg",
    gameId: "mkxl",
    id: "the-kove",
    kind: gameIconKinds.stage,
    src: new URL("./stages/the-kove.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "The Pit stage",
    assetPath: "icons/game/mkxl/stages/the-pit.svg",
    gameId: "mkxl",
    id: "the-pit",
    kind: gameIconKinds.stage,
    src: new URL("./stages/the-pit.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Training Room stage",
    assetPath: "icons/game/mkxl/stages/training-room.svg",
    gameId: "mkxl",
    id: "training-room",
    kind: gameIconKinds.stage,
    src: new URL("./stages/training-room.svg", import.meta.url).href,
  },
] as const satisfies readonly GameIconAsset[];
