import type { GameIconAsset } from "../type";
import { gameIconKinds } from "../value";

export const mkxlVariationIcons = [
  {
    accessibleLabel: "Tarkatan variation",
    assetPath: "icons/game/mkxl/variations/alien/tarkatan.svg",
    gameId: "mkxl",
    id: "alien:tarkatan",
    kind: gameIconKinds.variation,
    parentId: "alien",
    src: new URL("./variations/alien/tarkatan.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Acidic variation",
    assetPath: "icons/game/mkxl/variations/alien/acidic.svg",
    gameId: "mkxl",
    id: "alien:acidic",
    kind: gameIconKinds.variation,
    parentId: "alien",
    src: new URL("./variations/alien/acidic.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Konjurer variation",
    assetPath: "icons/game/mkxl/variations/alien/konjurer.svg",
    gameId: "mkxl",
    id: "alien:konjurer",
    kind: gameIconKinds.variation,
    parentId: "alien",
    src: new URL("./variations/alien/konjurer.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Bartitsu variation",
    assetPath: "icons/game/mkxl/variations/bo-rai-cho/bartitsu.svg",
    gameId: "mkxl",
    id: "bo-rai-cho:bartitsu",
    kind: gameIconKinds.variation,
    parentId: "bo-rai-cho",
    src: new URL("./variations/bo-rai-cho/bartitsu.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Dragon Breath variation",
    assetPath: "icons/game/mkxl/variations/bo-rai-cho/dragon-breath.svg",
    gameId: "mkxl",
    id: "bo-rai-cho:dragon-breath",
    kind: gameIconKinds.variation,
    parentId: "bo-rai-cho",
    src: new URL("./variations/bo-rai-cho/dragon-breath.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Drunken Master variation",
    assetPath: "icons/game/mkxl/variations/bo-rai-cho/drunken-master.svg",
    gameId: "mkxl",
    id: "bo-rai-cho:drunken-master",
    kind: gameIconKinds.variation,
    parentId: "bo-rai-cho",
    src: new URL("./variations/bo-rai-cho/drunken-master.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Spec Ops variation",
    assetPath: "icons/game/mkxl/variations/cassie-cage/spec-ops.svg",
    gameId: "mkxl",
    id: "cassie-cage:spec-ops",
    kind: gameIconKinds.variation,
    parentId: "cassie-cage",
    src: new URL("./variations/cassie-cage/spec-ops.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Hollywood variation",
    assetPath: "icons/game/mkxl/variations/cassie-cage/hollywood.svg",
    gameId: "mkxl",
    id: "cassie-cage:hollywood",
    kind: gameIconKinds.variation,
    parentId: "cassie-cage",
    src: new URL("./variations/cassie-cage/hollywood.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Brawler variation",
    assetPath: "icons/game/mkxl/variations/cassie-cage/brawler.svg",
    gameId: "mkxl",
    id: "cassie-cage:brawler",
    kind: gameIconKinds.variation,
    parentId: "cassie-cage",
    src: new URL("./variations/cassie-cage/brawler.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Venomous variation",
    assetPath: "icons/game/mkxl/variations/dvorah/venomous.svg",
    gameId: "mkxl",
    id: "dvorah:venomous",
    kind: gameIconKinds.variation,
    parentId: "dvorah",
    src: new URL("./variations/dvorah/venomous.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Brood Mother variation",
    assetPath: "icons/game/mkxl/variations/dvorah/brood-mother.svg",
    gameId: "mkxl",
    id: "dvorah:brood-mother",
    kind: gameIconKinds.variation,
    parentId: "dvorah",
    src: new URL("./variations/dvorah/brood-mother.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Swarm Queen variation",
    assetPath: "icons/game/mkxl/variations/dvorah/swarm-queen.svg",
    gameId: "mkxl",
    id: "dvorah:swarm-queen",
    kind: gameIconKinds.variation,
    parentId: "dvorah",
    src: new URL("./variations/dvorah/swarm-queen.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Spectral variation",
    assetPath: "icons/game/mkxl/variations/ermac/spectral.svg",
    gameId: "mkxl",
    id: "ermac:spectral",
    kind: gameIconKinds.variation,
    parentId: "ermac",
    src: new URL("./variations/ermac/spectral.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Mystic variation",
    assetPath: "icons/game/mkxl/variations/ermac/mystic.svg",
    gameId: "mkxl",
    id: "ermac:mystic",
    kind: gameIconKinds.variation,
    parentId: "ermac",
    src: new URL("./variations/ermac/mystic.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Master of Souls variation",
    assetPath: "icons/game/mkxl/variations/ermac/master-of-souls.svg",
    gameId: "mkxl",
    id: "ermac:master-of-souls",
    kind: gameIconKinds.variation,
    parentId: "ermac",
    src: new URL("./variations/ermac/master-of-souls.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Marksman variation",
    assetPath: "icons/game/mkxl/variations/erron-black/marksman.svg",
    gameId: "mkxl",
    id: "erron-black:marksman",
    kind: gameIconKinds.variation,
    parentId: "erron-black",
    src: new URL("./variations/erron-black/marksman.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Gunslinger variation",
    assetPath: "icons/game/mkxl/variations/erron-black/gunslinger.svg",
    gameId: "mkxl",
    id: "erron-black:gunslinger",
    kind: gameIconKinds.variation,
    parentId: "erron-black",
    src: new URL("./variations/erron-black/gunslinger.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Outlaw variation",
    assetPath: "icons/game/mkxl/variations/erron-black/outlaw.svg",
    gameId: "mkxl",
    id: "erron-black:outlaw",
    kind: gameIconKinds.variation,
    parentId: "erron-black",
    src: new URL("./variations/erron-black/outlaw.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Lackey variation",
    assetPath: "icons/game/mkxl/variations/ferra-torr/lackey.svg",
    gameId: "mkxl",
    id: "ferra-torr:lackey",
    kind: gameIconKinds.variation,
    parentId: "ferra-torr",
    src: new URL("./variations/ferra-torr/lackey.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ruthless variation",
    assetPath: "icons/game/mkxl/variations/ferra-torr/ruthless.svg",
    gameId: "mkxl",
    id: "ferra-torr:ruthless",
    kind: gameIconKinds.variation,
    parentId: "ferra-torr",
    src: new URL("./variations/ferra-torr/ruthless.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Vicious variation",
    assetPath: "icons/game/mkxl/variations/ferra-torr/vicious.svg",
    gameId: "mkxl",
    id: "ferra-torr:vicious",
    kind: gameIconKinds.variation,
    parentId: "ferra-torr",
    src: new URL("./variations/ferra-torr/vicious.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Tigrar Fury variation",
    assetPath: "icons/game/mkxl/variations/goro/tigrar-fury.svg",
    gameId: "mkxl",
    id: "goro:tigrar-fury",
    kind: gameIconKinds.variation,
    parentId: "goro",
    src: new URL("./variations/goro/tigrar-fury.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kuatan Warrior variation",
    assetPath: "icons/game/mkxl/variations/goro/kuatan-warrior.svg",
    gameId: "mkxl",
    id: "goro:kuatan-warrior",
    kind: gameIconKinds.variation,
    parentId: "goro",
    src: new URL("./variations/goro/kuatan-warrior.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Dragon Fangs variation",
    assetPath: "icons/game/mkxl/variations/goro/dragon-fangs.svg",
    gameId: "mkxl",
    id: "goro:dragon-fangs",
    kind: gameIconKinds.variation,
    parentId: "goro",
    src: new URL("./variations/goro/dragon-fangs.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "High Tech variation",
    assetPath: "icons/game/mkxl/variations/jacqui-briggs/high-tech.svg",
    gameId: "mkxl",
    id: "jacqui-briggs:high-tech",
    kind: gameIconKinds.variation,
    parentId: "jacqui-briggs",
    src: new URL("./variations/jacqui-briggs/high-tech.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Shotgun variation",
    assetPath: "icons/game/mkxl/variations/jacqui-briggs/shotgun.svg",
    gameId: "mkxl",
    id: "jacqui-briggs:shotgun",
    kind: gameIconKinds.variation,
    parentId: "jacqui-briggs",
    src: new URL("./variations/jacqui-briggs/shotgun.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Full Auto variation",
    assetPath: "icons/game/mkxl/variations/jacqui-briggs/full-auto.svg",
    gameId: "mkxl",
    id: "jacqui-briggs:full-auto",
    kind: gameIconKinds.variation,
    parentId: "jacqui-briggs",
    src: new URL("./variations/jacqui-briggs/full-auto.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Unstoppable variation",
    assetPath: "icons/game/mkxl/variations/jason-voorhees/unstoppable.svg",
    gameId: "mkxl",
    id: "jason-voorhees:unstoppable",
    kind: gameIconKinds.variation,
    parentId: "jason-voorhees",
    src: new URL("./variations/jason-voorhees/unstoppable.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Slasher variation",
    assetPath: "icons/game/mkxl/variations/jason-voorhees/slasher.svg",
    gameId: "mkxl",
    id: "jason-voorhees:slasher",
    kind: gameIconKinds.variation,
    parentId: "jason-voorhees",
    src: new URL("./variations/jason-voorhees/slasher.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Relentless variation",
    assetPath: "icons/game/mkxl/variations/jason-voorhees/relentless.svg",
    gameId: "mkxl",
    id: "jason-voorhees:relentless",
    kind: gameIconKinds.variation,
    parentId: "jason-voorhees",
    src: new URL("./variations/jason-voorhees/relentless.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Wrestler variation",
    assetPath: "icons/game/mkxl/variations/jax/wrestler.svg",
    gameId: "mkxl",
    id: "jax:wrestler",
    kind: gameIconKinds.variation,
    parentId: "jax",
    src: new URL("./variations/jax/wrestler.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Heavy Weapons variation",
    assetPath: "icons/game/mkxl/variations/jax/heavy-weapons.svg",
    gameId: "mkxl",
    id: "jax:heavy-weapons",
    kind: gameIconKinds.variation,
    parentId: "jax",
    src: new URL("./variations/jax/heavy-weapons.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Pumped Up variation",
    assetPath: "icons/game/mkxl/variations/jax/pumped-up.svg",
    gameId: "mkxl",
    id: "jax:pumped-up",
    kind: gameIconKinds.variation,
    parentId: "jax",
    src: new URL("./variations/jax/pumped-up.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "A-List variation",
    assetPath: "icons/game/mkxl/variations/johnny-cage/a-list.svg",
    gameId: "mkxl",
    id: "johnny-cage:a-list",
    kind: gameIconKinds.variation,
    parentId: "johnny-cage",
    src: new URL("./variations/johnny-cage/a-list.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Fisticuffs variation",
    assetPath: "icons/game/mkxl/variations/johnny-cage/fisticuffs.svg",
    gameId: "mkxl",
    id: "johnny-cage:fisticuffs",
    kind: gameIconKinds.variation,
    parentId: "johnny-cage",
    src: new URL("./variations/johnny-cage/fisticuffs.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Stunt Double variation",
    assetPath: "icons/game/mkxl/variations/johnny-cage/stunt-double.svg",
    gameId: "mkxl",
    id: "johnny-cage:stunt-double",
    kind: gameIconKinds.variation,
    parentId: "johnny-cage",
    src: new URL("./variations/johnny-cage/stunt-double.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Commando variation",
    assetPath: "icons/game/mkxl/variations/kano/commando.svg",
    gameId: "mkxl",
    id: "kano:commando",
    kind: gameIconKinds.variation,
    parentId: "kano",
    src: new URL("./variations/kano/commando.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Cutthroat variation",
    assetPath: "icons/game/mkxl/variations/kano/cutthroat.svg",
    gameId: "mkxl",
    id: "kano:cutthroat",
    kind: gameIconKinds.variation,
    parentId: "kano",
    src: new URL("./variations/kano/cutthroat.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Cybernetic variation",
    assetPath: "icons/game/mkxl/variations/kano/cybernetic.svg",
    gameId: "mkxl",
    id: "kano:cybernetic",
    kind: gameIconKinds.variation,
    parentId: "kano",
    src: new URL("./variations/kano/cybernetic.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kenjutsu variation",
    assetPath: "icons/game/mkxl/variations/kenshi/kenjutsu.svg",
    gameId: "mkxl",
    id: "kenshi:kenjutsu",
    kind: gameIconKinds.variation,
    parentId: "kenshi",
    src: new URL("./variations/kenshi/kenjutsu.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Balanced variation",
    assetPath: "icons/game/mkxl/variations/kenshi/balanced.svg",
    gameId: "mkxl",
    id: "kenshi:balanced",
    kind: gameIconKinds.variation,
    parentId: "kenshi",
    src: new URL("./variations/kenshi/balanced.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Possessed variation",
    assetPath: "icons/game/mkxl/variations/kenshi/possessed.svg",
    gameId: "mkxl",
    id: "kenshi:possessed",
    kind: gameIconKinds.variation,
    parentId: "kenshi",
    src: new URL("./variations/kenshi/possessed.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Mournful variation",
    assetPath: "icons/game/mkxl/variations/kitana/mournful.svg",
    gameId: "mkxl",
    id: "kitana:mournful",
    kind: gameIconKinds.variation,
    parentId: "kitana",
    src: new URL("./variations/kitana/mournful.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Royal Storm variation",
    assetPath: "icons/game/mkxl/variations/kitana/royal-storm.svg",
    gameId: "mkxl",
    id: "kitana:royal-storm",
    kind: gameIconKinds.variation,
    parentId: "kitana",
    src: new URL("./variations/kitana/royal-storm.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Assassin variation",
    assetPath: "icons/game/mkxl/variations/kitana/assassin.svg",
    gameId: "mkxl",
    id: "kitana:assassin",
    kind: gameIconKinds.variation,
    parentId: "kitana",
    src: new URL("./variations/kitana/assassin.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Sun God variation",
    assetPath: "icons/game/mkxl/variations/kotal-kahn/sun-god.svg",
    gameId: "mkxl",
    id: "kotal-kahn:sun-god",
    kind: gameIconKinds.variation,
    parentId: "kotal-kahn",
    src: new URL("./variations/kotal-kahn/sun-god.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Blood God variation",
    assetPath: "icons/game/mkxl/variations/kotal-kahn/blood-god.svg",
    gameId: "mkxl",
    id: "kotal-kahn:blood-god",
    kind: gameIconKinds.variation,
    parentId: "kotal-kahn",
    src: new URL("./variations/kotal-kahn/blood-god.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "War God variation",
    assetPath: "icons/game/mkxl/variations/kotal-kahn/war-god.svg",
    gameId: "mkxl",
    id: "kotal-kahn:war-god",
    kind: gameIconKinds.variation,
    parentId: "kotal-kahn",
    src: new URL("./variations/kotal-kahn/war-god.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Shaolin variation",
    assetPath: "icons/game/mkxl/variations/kung-jin/shaolin.svg",
    gameId: "mkxl",
    id: "kung-jin:shaolin",
    kind: gameIconKinds.variation,
    parentId: "kung-jin",
    src: new URL("./variations/kung-jin/shaolin.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ancestral variation",
    assetPath: "icons/game/mkxl/variations/kung-jin/ancestral.svg",
    gameId: "mkxl",
    id: "kung-jin:ancestral",
    kind: gameIconKinds.variation,
    parentId: "kung-jin",
    src: new URL("./variations/kung-jin/ancestral.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Bojutsu variation",
    assetPath: "icons/game/mkxl/variations/kung-jin/bojutsu.svg",
    gameId: "mkxl",
    id: "kung-jin:bojutsu",
    kind: gameIconKinds.variation,
    parentId: "kung-jin",
    src: new URL("./variations/kung-jin/bojutsu.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Hat Trick variation",
    assetPath: "icons/game/mkxl/variations/kung-lao/hat-trick.svg",
    gameId: "mkxl",
    id: "kung-lao:hat-trick",
    kind: gameIconKinds.variation,
    parentId: "kung-lao",
    src: new URL("./variations/kung-lao/hat-trick.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Tempest variation",
    assetPath: "icons/game/mkxl/variations/kung-lao/tempest.svg",
    gameId: "mkxl",
    id: "kung-lao:tempest",
    kind: gameIconKinds.variation,
    parentId: "kung-lao",
    src: new URL("./variations/kung-lao/tempest.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Buzz Saw variation",
    assetPath: "icons/game/mkxl/variations/kung-lao/buzz-saw.svg",
    gameId: "mkxl",
    id: "kung-lao:buzz-saw",
    kind: gameIconKinds.variation,
    parentId: "kung-lao",
    src: new URL("./variations/kung-lao/buzz-saw.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Pretty Lady variation",
    assetPath: "icons/game/mkxl/variations/leatherface/pretty-lady.svg",
    gameId: "mkxl",
    id: "leatherface:pretty-lady",
    kind: gameIconKinds.variation,
    parentId: "leatherface",
    src: new URL("./variations/leatherface/pretty-lady.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Killer variation",
    assetPath: "icons/game/mkxl/variations/leatherface/killer.svg",
    gameId: "mkxl",
    id: "leatherface:killer",
    kind: gameIconKinds.variation,
    parentId: "leatherface",
    src: new URL("./variations/leatherface/killer.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Butcher variation",
    assetPath: "icons/game/mkxl/variations/leatherface/butcher.svg",
    gameId: "mkxl",
    id: "leatherface:butcher",
    kind: gameIconKinds.variation,
    parentId: "leatherface",
    src: new URL("./variations/leatherface/butcher.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Dualist variation",
    assetPath: "icons/game/mkxl/variations/liu-kang/dualist.svg",
    gameId: "mkxl",
    id: "liu-kang:dualist",
    kind: gameIconKinds.variation,
    parentId: "liu-kang",
    src: new URL("./variations/liu-kang/dualist.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Flame Fist variation",
    assetPath: "icons/game/mkxl/variations/liu-kang/flame-fist.svg",
    gameId: "mkxl",
    id: "liu-kang:flame-fist",
    kind: gameIconKinds.variation,
    parentId: "liu-kang",
    src: new URL("./variations/liu-kang/flame-fist.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Dragon's Fire variation",
    assetPath: "icons/game/mkxl/variations/liu-kang/dragons-fire.svg",
    gameId: "mkxl",
    id: "liu-kang:dragons-fire",
    kind: gameIconKinds.variation,
    parentId: "liu-kang",
    src: new URL("./variations/liu-kang/dragons-fire.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ravenous variation",
    assetPath: "icons/game/mkxl/variations/mileena/ravenous.svg",
    gameId: "mkxl",
    id: "mileena:ravenous",
    kind: gameIconKinds.variation,
    parentId: "mileena",
    src: new URL("./variations/mileena/ravenous.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Piercing variation",
    assetPath: "icons/game/mkxl/variations/mileena/piercing.svg",
    gameId: "mkxl",
    id: "mileena:piercing",
    kind: gameIconKinds.variation,
    parentId: "mileena",
    src: new URL("./variations/mileena/piercing.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ethereal variation",
    assetPath: "icons/game/mkxl/variations/mileena/ethereal.svg",
    gameId: "mkxl",
    id: "mileena:ethereal",
    kind: gameIconKinds.variation,
    parentId: "mileena",
    src: new URL("./variations/mileena/ethereal.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Hish-Qu-Ten variation",
    assetPath: "icons/game/mkxl/variations/predator/hish-qu-ten.svg",
    gameId: "mkxl",
    id: "predator:hish-qu-ten",
    kind: gameIconKinds.variation,
    parentId: "predator",
    src: new URL("./variations/predator/hish-qu-ten.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Warrior variation",
    assetPath: "icons/game/mkxl/variations/predator/warrior.svg",
    gameId: "mkxl",
    id: "predator:warrior",
    kind: gameIconKinds.variation,
    parentId: "predator",
    src: new URL("./variations/predator/warrior.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Hunter variation",
    assetPath: "icons/game/mkxl/variations/predator/hunter.svg",
    gameId: "mkxl",
    id: "predator:hunter",
    kind: gameIconKinds.variation,
    parentId: "predator",
    src: new URL("./variations/predator/hunter.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Summoner variation",
    assetPath: "icons/game/mkxl/variations/quan-chi/summoner.svg",
    gameId: "mkxl",
    id: "quan-chi:summoner",
    kind: gameIconKinds.variation,
    parentId: "quan-chi",
    src: new URL("./variations/quan-chi/summoner.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Warlock variation",
    assetPath: "icons/game/mkxl/variations/quan-chi/warlock.svg",
    gameId: "mkxl",
    id: "quan-chi:warlock",
    kind: gameIconKinds.variation,
    parentId: "quan-chi",
    src: new URL("./variations/quan-chi/warlock.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Sorcerer variation",
    assetPath: "icons/game/mkxl/variations/quan-chi/sorcerer.svg",
    gameId: "mkxl",
    id: "quan-chi:sorcerer",
    kind: gameIconKinds.variation,
    parentId: "quan-chi",
    src: new URL("./variations/quan-chi/sorcerer.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Thunder God variation",
    assetPath: "icons/game/mkxl/variations/raiden/thunder-god.svg",
    gameId: "mkxl",
    id: "raiden:thunder-god",
    kind: gameIconKinds.variation,
    parentId: "raiden",
    src: new URL("./variations/raiden/thunder-god.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Displacer variation",
    assetPath: "icons/game/mkxl/variations/raiden/displacer.svg",
    gameId: "mkxl",
    id: "raiden:displacer",
    kind: gameIconKinds.variation,
    parentId: "raiden",
    src: new URL("./variations/raiden/displacer.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Master of Storms variation",
    assetPath: "icons/game/mkxl/variations/raiden/master-of-storms.svg",
    gameId: "mkxl",
    id: "raiden:master-of-storms",
    kind: gameIconKinds.variation,
    parentId: "raiden",
    src: new URL("./variations/raiden/master-of-storms.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Noxious variation",
    assetPath: "icons/game/mkxl/variations/reptile/noxious.svg",
    gameId: "mkxl",
    id: "reptile:noxious",
    kind: gameIconKinds.variation,
    parentId: "reptile",
    src: new URL("./variations/reptile/noxious.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Deceptive variation",
    assetPath: "icons/game/mkxl/variations/reptile/deceptive.svg",
    gameId: "mkxl",
    id: "reptile:deceptive",
    kind: gameIconKinds.variation,
    parentId: "reptile",
    src: new URL("./variations/reptile/deceptive.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Nimble variation",
    assetPath: "icons/game/mkxl/variations/reptile/nimble.svg",
    gameId: "mkxl",
    id: "reptile:nimble",
    kind: gameIconKinds.variation,
    parentId: "reptile",
    src: new URL("./variations/reptile/nimble.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Inferno variation",
    assetPath: "icons/game/mkxl/variations/scorpion/inferno.svg",
    gameId: "mkxl",
    id: "scorpion:inferno",
    kind: gameIconKinds.variation,
    parentId: "scorpion",
    src: new URL("./variations/scorpion/inferno.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ninjutsu variation",
    assetPath: "icons/game/mkxl/variations/scorpion/ninjutsu.svg",
    gameId: "mkxl",
    id: "scorpion:ninjutsu",
    kind: gameIconKinds.variation,
    parentId: "scorpion",
    src: new URL("./variations/scorpion/ninjutsu.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Hellfire variation",
    assetPath: "icons/game/mkxl/variations/scorpion/hellfire.svg",
    gameId: "mkxl",
    id: "scorpion:hellfire",
    kind: gameIconKinds.variation,
    parentId: "scorpion",
    src: new URL("./variations/scorpion/hellfire.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Necromancer variation",
    assetPath: "icons/game/mkxl/variations/shinnok/necromancer.svg",
    gameId: "mkxl",
    id: "shinnok:necromancer",
    kind: gameIconKinds.variation,
    parentId: "shinnok",
    src: new URL("./variations/shinnok/necromancer.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Impostor variation",
    assetPath: "icons/game/mkxl/variations/shinnok/impostor.svg",
    gameId: "mkxl",
    id: "shinnok:impostor",
    kind: gameIconKinds.variation,
    parentId: "shinnok",
    src: new URL("./variations/shinnok/impostor.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Bone Shaper variation",
    assetPath: "icons/game/mkxl/variations/shinnok/bone-shaper.svg",
    gameId: "mkxl",
    id: "shinnok:bone-shaper",
    kind: gameIconKinds.variation,
    parentId: "shinnok",
    src: new URL("./variations/shinnok/bone-shaper.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Covert Ops variation",
    assetPath: "icons/game/mkxl/variations/sonya-blade/covert-ops.svg",
    gameId: "mkxl",
    id: "sonya-blade:covert-ops",
    kind: gameIconKinds.variation,
    parentId: "sonya-blade",
    src: new URL("./variations/sonya-blade/covert-ops.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Special Forces variation",
    assetPath: "icons/game/mkxl/variations/sonya-blade/special-forces.svg",
    gameId: "mkxl",
    id: "sonya-blade:special-forces",
    kind: gameIconKinds.variation,
    parentId: "sonya-blade",
    src: new URL("./variations/sonya-blade/special-forces.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Demolition variation",
    assetPath: "icons/game/mkxl/variations/sonya-blade/demolition.svg",
    gameId: "mkxl",
    id: "sonya-blade:demolition",
    kind: gameIconKinds.variation,
    parentId: "sonya-blade",
    src: new URL("./variations/sonya-blade/demolition.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Grandmaster variation",
    assetPath: "icons/game/mkxl/variations/sub-zero/grandmaster.svg",
    gameId: "mkxl",
    id: "sub-zero:grandmaster",
    kind: gameIconKinds.variation,
    parentId: "sub-zero",
    src: new URL("./variations/sub-zero/grandmaster.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Cryomancer variation",
    assetPath: "icons/game/mkxl/variations/sub-zero/cryomancer.svg",
    gameId: "mkxl",
    id: "sub-zero:cryomancer",
    kind: gameIconKinds.variation,
    parentId: "sub-zero",
    src: new URL("./variations/sub-zero/cryomancer.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Unbreakable variation",
    assetPath: "icons/game/mkxl/variations/sub-zero/unbreakable.svg",
    gameId: "mkxl",
    id: "sub-zero:unbreakable",
    kind: gameIconKinds.variation,
    parentId: "sub-zero",
    src: new URL("./variations/sub-zero/unbreakable.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Ronin variation",
    assetPath: "icons/game/mkxl/variations/takeda/ronin.svg",
    gameId: "mkxl",
    id: "takeda:ronin",
    kind: gameIconKinds.variation,
    parentId: "takeda",
    src: new URL("./variations/takeda/ronin.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Shirai Ryu variation",
    assetPath: "icons/game/mkxl/variations/takeda/shirai-ryu.svg",
    gameId: "mkxl",
    id: "takeda:shirai-ryu",
    kind: gameIconKinds.variation,
    parentId: "takeda",
    src: new URL("./variations/takeda/shirai-ryu.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Lasher variation",
    assetPath: "icons/game/mkxl/variations/takeda/lasher.svg",
    gameId: "mkxl",
    id: "takeda:lasher",
    kind: gameIconKinds.variation,
    parentId: "takeda",
    src: new URL("./variations/takeda/lasher.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Pyromancer variation",
    assetPath: "icons/game/mkxl/variations/tanya/pyromancer.svg",
    gameId: "mkxl",
    id: "tanya:pyromancer",
    kind: gameIconKinds.variation,
    parentId: "tanya",
    src: new URL("./variations/tanya/pyromancer.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Kobu Jutsu variation",
    assetPath: "icons/game/mkxl/variations/tanya/kobu-jutsu.svg",
    gameId: "mkxl",
    id: "tanya:kobu-jutsu",
    kind: gameIconKinds.variation,
    parentId: "tanya",
    src: new URL("./variations/tanya/kobu-jutsu.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Dragon Naginata variation",
    assetPath: "icons/game/mkxl/variations/tanya/dragon-naginata.svg",
    gameId: "mkxl",
    id: "tanya:dragon-naginata",
    kind: gameIconKinds.variation,
    parentId: "tanya",
    src: new URL("./variations/tanya/dragon-naginata.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Crystalline variation",
    assetPath: "icons/game/mkxl/variations/tremor/crystalline.svg",
    gameId: "mkxl",
    id: "tremor:crystalline",
    kind: gameIconKinds.variation,
    parentId: "tremor",
    src: new URL("./variations/tremor/crystalline.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Aftershock variation",
    assetPath: "icons/game/mkxl/variations/tremor/aftershock.svg",
    gameId: "mkxl",
    id: "tremor:aftershock",
    kind: gameIconKinds.variation,
    parentId: "tremor",
    src: new URL("./variations/tremor/aftershock.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Metallic variation",
    assetPath: "icons/game/mkxl/variations/tremor/metallic.svg",
    gameId: "mkxl",
    id: "tremor:metallic",
    kind: gameIconKinds.variation,
    parentId: "tremor",
    src: new URL("./variations/tremor/metallic.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Smoke variation",
    assetPath: "icons/game/mkxl/variations/triborg/smoke.svg",
    gameId: "mkxl",
    id: "triborg:smoke",
    kind: gameIconKinds.variation,
    parentId: "triborg",
    src: new URL("./variations/triborg/smoke.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Sektor variation",
    assetPath: "icons/game/mkxl/variations/triborg/sektor.svg",
    gameId: "mkxl",
    id: "triborg:sektor",
    kind: gameIconKinds.variation,
    parentId: "triborg",
    src: new URL("./variations/triborg/sektor.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Cyrax variation",
    assetPath: "icons/game/mkxl/variations/triborg/cyrax.svg",
    gameId: "mkxl",
    id: "triborg:cyrax",
    kind: gameIconKinds.variation,
    parentId: "triborg",
    src: new URL("./variations/triborg/cyrax.svg", import.meta.url).href,
  },
  {
    accessibleLabel: "Cyber Sub-Zero variation",
    assetPath: "icons/game/mkxl/variations/triborg/cyber-sub-zero.svg",
    gameId: "mkxl",
    id: "triborg:cyber-sub-zero",
    kind: gameIconKinds.variation,
    parentId: "triborg",
    src: new URL("./variations/triborg/cyber-sub-zero.svg", import.meta.url).href,
  },
] as const satisfies readonly GameIconAsset[];
