/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AppRouteRouteImport } from "./routes/_app/route";
import { Route as AppIndexRouteImport } from "./routes/_app/index";
import { Route as AppSplatRouteImport } from "./routes/_app/$";
import { Route as AppGameIdRouteRouteImport } from "./routes/_app/$gameId/route";
import { Route as AppGameIdIndexRouteImport } from "./routes/_app/$gameId/index";
import { Route as AppGameIdListsRouteImport } from "./routes/_app/$gameId/lists";
import { Route as AppGameIdBuilderRouteImport } from "./routes/_app/$gameId/builder";
import { Route as AppGameIdCatalogRouteRouteImport } from "./routes/_app/$gameId/catalog/route";
import { Route as AppGameIdCatalogIndexRouteImport } from "./routes/_app/$gameId/catalog/index";
import { Route as AppGameIdCatalogCharacterRouteRouteImport } from "./routes/_app/$gameId/catalog/$character/route";
import { Route as AppGameIdCatalogCharacterIndexRouteImport } from "./routes/_app/$gameId/catalog/$character/index";
import { Route as AppGameIdCatalogCharacterSpecificationRouteRouteImport } from "./routes/_app/$gameId/catalog/$character/$specification/route";
import { Route as AppGameIdCatalogCharacterSpecificationIndexRouteImport } from "./routes/_app/$gameId/catalog/$character/$specification/index";
import { Route as AppGameIdCatalogCharacterSpecificationComboIdRouteImport } from "./routes/_app/$gameId/catalog/$character/$specification/$comboId";

const AppRouteRoute = AppRouteRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppSplatRoute = AppSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppGameIdRouteRoute = AppGameIdRouteRouteImport.update({
  id: "/$gameId",
  path: "/$gameId",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppGameIdIndexRoute = AppGameIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppGameIdRouteRoute,
} as any);
const AppGameIdListsRoute = AppGameIdListsRouteImport.update({
  id: "/lists",
  path: "/lists",
  getParentRoute: () => AppGameIdRouteRoute,
} as any);
const AppGameIdBuilderRoute = AppGameIdBuilderRouteImport.update({
  id: "/builder",
  path: "/builder",
  getParentRoute: () => AppGameIdRouteRoute,
} as any);
const AppGameIdCatalogRouteRoute = AppGameIdCatalogRouteRouteImport.update({
  id: "/catalog",
  path: "/catalog",
  getParentRoute: () => AppGameIdRouteRoute,
} as any);
const AppGameIdCatalogIndexRoute = AppGameIdCatalogIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppGameIdCatalogRouteRoute,
} as any);
const AppGameIdCatalogCharacterRouteRoute =
  AppGameIdCatalogCharacterRouteRouteImport.update({
    id: "/$character",
    path: "/$character",
    getParentRoute: () => AppGameIdCatalogRouteRoute,
  } as any);
const AppGameIdCatalogCharacterIndexRoute =
  AppGameIdCatalogCharacterIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppGameIdCatalogCharacterRouteRoute,
  } as any);
const AppGameIdCatalogCharacterSpecificationRouteRoute =
  AppGameIdCatalogCharacterSpecificationRouteRouteImport.update({
    id: "/$specification",
    path: "/$specification",
    getParentRoute: () => AppGameIdCatalogCharacterRouteRoute,
  } as any);
const AppGameIdCatalogCharacterSpecificationIndexRoute =
  AppGameIdCatalogCharacterSpecificationIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppGameIdCatalogCharacterSpecificationRouteRoute,
  } as any);
const AppGameIdCatalogCharacterSpecificationComboIdRoute =
  AppGameIdCatalogCharacterSpecificationComboIdRouteImport.update({
    id: "/$comboId",
    path: "/$comboId",
    getParentRoute: () => AppGameIdCatalogCharacterSpecificationRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute;
  "/$gameId": typeof AppGameIdRouteRouteWithChildren;
  "/$": typeof AppSplatRoute;
  "/$gameId/catalog": typeof AppGameIdCatalogRouteRouteWithChildren;
  "/$gameId/builder": typeof AppGameIdBuilderRoute;
  "/$gameId/lists": typeof AppGameIdListsRoute;
  "/$gameId/": typeof AppGameIdIndexRoute;
  "/$gameId/catalog/$character": typeof AppGameIdCatalogCharacterRouteRouteWithChildren;
  "/$gameId/catalog/": typeof AppGameIdCatalogIndexRoute;
  "/$gameId/catalog/$character/$specification": typeof AppGameIdCatalogCharacterSpecificationRouteRouteWithChildren;
  "/$gameId/catalog/$character/": typeof AppGameIdCatalogCharacterIndexRoute;
  "/$gameId/catalog/$character/$specification/$comboId": typeof AppGameIdCatalogCharacterSpecificationComboIdRoute;
  "/$gameId/catalog/$character/$specification/": typeof AppGameIdCatalogCharacterSpecificationIndexRoute;
}
export interface FileRoutesByTo {
  "/$": typeof AppSplatRoute;
  "/": typeof AppIndexRoute;
  "/$gameId/builder": typeof AppGameIdBuilderRoute;
  "/$gameId/lists": typeof AppGameIdListsRoute;
  "/$gameId": typeof AppGameIdIndexRoute;
  "/$gameId/catalog": typeof AppGameIdCatalogIndexRoute;
  "/$gameId/catalog/$character": typeof AppGameIdCatalogCharacterIndexRoute;
  "/$gameId/catalog/$character/$specification/$comboId": typeof AppGameIdCatalogCharacterSpecificationComboIdRoute;
  "/$gameId/catalog/$character/$specification": typeof AppGameIdCatalogCharacterSpecificationIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppRouteRouteWithChildren;
  "/_app/$gameId": typeof AppGameIdRouteRouteWithChildren;
  "/_app/$": typeof AppSplatRoute;
  "/_app/": typeof AppIndexRoute;
  "/_app/$gameId/catalog": typeof AppGameIdCatalogRouteRouteWithChildren;
  "/_app/$gameId/builder": typeof AppGameIdBuilderRoute;
  "/_app/$gameId/lists": typeof AppGameIdListsRoute;
  "/_app/$gameId/": typeof AppGameIdIndexRoute;
  "/_app/$gameId/catalog/$character": typeof AppGameIdCatalogCharacterRouteRouteWithChildren;
  "/_app/$gameId/catalog/": typeof AppGameIdCatalogIndexRoute;
  "/_app/$gameId/catalog/$character/$specification": typeof AppGameIdCatalogCharacterSpecificationRouteRouteWithChildren;
  "/_app/$gameId/catalog/$character/": typeof AppGameIdCatalogCharacterIndexRoute;
  "/_app/$gameId/catalog/$character/$specification/$comboId": typeof AppGameIdCatalogCharacterSpecificationComboIdRoute;
  "/_app/$gameId/catalog/$character/$specification/": typeof AppGameIdCatalogCharacterSpecificationIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$gameId"
    | "/$"
    | "/$gameId/catalog"
    | "/$gameId/builder"
    | "/$gameId/lists"
    | "/$gameId/"
    | "/$gameId/catalog/$character"
    | "/$gameId/catalog/"
    | "/$gameId/catalog/$character/$specification"
    | "/$gameId/catalog/$character/"
    | "/$gameId/catalog/$character/$specification/$comboId"
    | "/$gameId/catalog/$character/$specification/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/$"
    | "/"
    | "/$gameId/builder"
    | "/$gameId/lists"
    | "/$gameId"
    | "/$gameId/catalog"
    | "/$gameId/catalog/$character"
    | "/$gameId/catalog/$character/$specification/$comboId"
    | "/$gameId/catalog/$character/$specification";
  id:
    | "__root__"
    | "/_app"
    | "/_app/$gameId"
    | "/_app/$"
    | "/_app/"
    | "/_app/$gameId/catalog"
    | "/_app/$gameId/builder"
    | "/_app/$gameId/lists"
    | "/_app/$gameId/"
    | "/_app/$gameId/catalog/$character"
    | "/_app/$gameId/catalog/"
    | "/_app/$gameId/catalog/$character/$specification"
    | "/_app/$gameId/catalog/$character/"
    | "/_app/$gameId/catalog/$character/$specification/$comboId"
    | "/_app/$gameId/catalog/$character/$specification/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/$": {
      id: "/_app/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof AppSplatRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/$gameId": {
      id: "/_app/$gameId";
      path: "/$gameId";
      fullPath: "/$gameId";
      preLoaderRoute: typeof AppGameIdRouteRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/$gameId/": {
      id: "/_app/$gameId/";
      path: "/";
      fullPath: "/$gameId/";
      preLoaderRoute: typeof AppGameIdIndexRouteImport;
      parentRoute: typeof AppGameIdRouteRoute;
    };
    "/_app/$gameId/lists": {
      id: "/_app/$gameId/lists";
      path: "/lists";
      fullPath: "/$gameId/lists";
      preLoaderRoute: typeof AppGameIdListsRouteImport;
      parentRoute: typeof AppGameIdRouteRoute;
    };
    "/_app/$gameId/builder": {
      id: "/_app/$gameId/builder";
      path: "/builder";
      fullPath: "/$gameId/builder";
      preLoaderRoute: typeof AppGameIdBuilderRouteImport;
      parentRoute: typeof AppGameIdRouteRoute;
    };
    "/_app/$gameId/catalog": {
      id: "/_app/$gameId/catalog";
      path: "/catalog";
      fullPath: "/$gameId/catalog";
      preLoaderRoute: typeof AppGameIdCatalogRouteRouteImport;
      parentRoute: typeof AppGameIdRouteRoute;
    };
    "/_app/$gameId/catalog/": {
      id: "/_app/$gameId/catalog/";
      path: "/";
      fullPath: "/$gameId/catalog/";
      preLoaderRoute: typeof AppGameIdCatalogIndexRouteImport;
      parentRoute: typeof AppGameIdCatalogRouteRoute;
    };
    "/_app/$gameId/catalog/$character": {
      id: "/_app/$gameId/catalog/$character";
      path: "/$character";
      fullPath: "/$gameId/catalog/$character";
      preLoaderRoute: typeof AppGameIdCatalogCharacterRouteRouteImport;
      parentRoute: typeof AppGameIdCatalogRouteRoute;
    };
    "/_app/$gameId/catalog/$character/": {
      id: "/_app/$gameId/catalog/$character/";
      path: "/";
      fullPath: "/$gameId/catalog/$character/";
      preLoaderRoute: typeof AppGameIdCatalogCharacterIndexRouteImport;
      parentRoute: typeof AppGameIdCatalogCharacterRouteRoute;
    };
    "/_app/$gameId/catalog/$character/$specification": {
      id: "/_app/$gameId/catalog/$character/$specification";
      path: "/$specification";
      fullPath: "/$gameId/catalog/$character/$specification";
      preLoaderRoute: typeof AppGameIdCatalogCharacterSpecificationRouteRouteImport;
      parentRoute: typeof AppGameIdCatalogCharacterRouteRoute;
    };
    "/_app/$gameId/catalog/$character/$specification/": {
      id: "/_app/$gameId/catalog/$character/$specification/";
      path: "/";
      fullPath: "/$gameId/catalog/$character/$specification/";
      preLoaderRoute: typeof AppGameIdCatalogCharacterSpecificationIndexRouteImport;
      parentRoute: typeof AppGameIdCatalogCharacterSpecificationRouteRoute;
    };
    "/_app/$gameId/catalog/$character/$specification/$comboId": {
      id: "/_app/$gameId/catalog/$character/$specification/$comboId";
      path: "/$comboId";
      fullPath: "/$gameId/catalog/$character/$specification/$comboId";
      preLoaderRoute: typeof AppGameIdCatalogCharacterSpecificationComboIdRouteImport;
      parentRoute: typeof AppGameIdCatalogCharacterSpecificationRouteRoute;
    };
  }
}

interface AppGameIdCatalogCharacterSpecificationRouteRouteChildren {
  AppGameIdCatalogCharacterSpecificationComboIdRoute: typeof AppGameIdCatalogCharacterSpecificationComboIdRoute;
  AppGameIdCatalogCharacterSpecificationIndexRoute: typeof AppGameIdCatalogCharacterSpecificationIndexRoute;
}

const AppGameIdCatalogCharacterSpecificationRouteRouteChildren: AppGameIdCatalogCharacterSpecificationRouteRouteChildren =
  {
    AppGameIdCatalogCharacterSpecificationComboIdRoute:
      AppGameIdCatalogCharacterSpecificationComboIdRoute,
    AppGameIdCatalogCharacterSpecificationIndexRoute:
      AppGameIdCatalogCharacterSpecificationIndexRoute,
  };

const AppGameIdCatalogCharacterSpecificationRouteRouteWithChildren =
  AppGameIdCatalogCharacterSpecificationRouteRoute._addFileChildren(
    AppGameIdCatalogCharacterSpecificationRouteRouteChildren,
  );

interface AppGameIdCatalogCharacterRouteRouteChildren {
  AppGameIdCatalogCharacterSpecificationRouteRoute: typeof AppGameIdCatalogCharacterSpecificationRouteRouteWithChildren;
  AppGameIdCatalogCharacterIndexRoute: typeof AppGameIdCatalogCharacterIndexRoute;
}

const AppGameIdCatalogCharacterRouteRouteChildren: AppGameIdCatalogCharacterRouteRouteChildren =
  {
    AppGameIdCatalogCharacterSpecificationRouteRoute:
      AppGameIdCatalogCharacterSpecificationRouteRouteWithChildren,
    AppGameIdCatalogCharacterIndexRoute: AppGameIdCatalogCharacterIndexRoute,
  };

const AppGameIdCatalogCharacterRouteRouteWithChildren =
  AppGameIdCatalogCharacterRouteRoute._addFileChildren(
    AppGameIdCatalogCharacterRouteRouteChildren,
  );

interface AppGameIdCatalogRouteRouteChildren {
  AppGameIdCatalogCharacterRouteRoute: typeof AppGameIdCatalogCharacterRouteRouteWithChildren;
  AppGameIdCatalogIndexRoute: typeof AppGameIdCatalogIndexRoute;
}

const AppGameIdCatalogRouteRouteChildren: AppGameIdCatalogRouteRouteChildren = {
  AppGameIdCatalogCharacterRouteRoute:
    AppGameIdCatalogCharacterRouteRouteWithChildren,
  AppGameIdCatalogIndexRoute: AppGameIdCatalogIndexRoute,
};

const AppGameIdCatalogRouteRouteWithChildren =
  AppGameIdCatalogRouteRoute._addFileChildren(
    AppGameIdCatalogRouteRouteChildren,
  );

interface AppGameIdRouteRouteChildren {
  AppGameIdCatalogRouteRoute: typeof AppGameIdCatalogRouteRouteWithChildren;
  AppGameIdBuilderRoute: typeof AppGameIdBuilderRoute;
  AppGameIdListsRoute: typeof AppGameIdListsRoute;
  AppGameIdIndexRoute: typeof AppGameIdIndexRoute;
}

const AppGameIdRouteRouteChildren: AppGameIdRouteRouteChildren = {
  AppGameIdCatalogRouteRoute: AppGameIdCatalogRouteRouteWithChildren,
  AppGameIdBuilderRoute: AppGameIdBuilderRoute,
  AppGameIdListsRoute: AppGameIdListsRoute,
  AppGameIdIndexRoute: AppGameIdIndexRoute,
};

const AppGameIdRouteRouteWithChildren = AppGameIdRouteRoute._addFileChildren(
  AppGameIdRouteRouteChildren,
);

interface AppRouteRouteChildren {
  AppGameIdRouteRoute: typeof AppGameIdRouteRouteWithChildren;
  AppSplatRoute: typeof AppSplatRoute;
  AppIndexRoute: typeof AppIndexRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGameIdRouteRoute: AppGameIdRouteRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
