import { notationDisplayModes } from "@mk-combos/contracts/settings/value";

import {
  backupDisclosureStates,
  backupOperationStates,
  backupPersistenceModes,
  backupSliceStatuses,
  backupValidationMessageTones,
  backupValidationStatuses,
  componentInteractionReasons,
  componentOptionStatuses,
  controllerAccessStates,
  uiResponsiveModes,
} from "./components/value";
import { uiFocusDirections } from "./focus-navigation/value";
import { uiNotationIconKinds, uiNotationTokenStates, uiNotationTokens } from "./notation/value";
import { uiPrimitiveInteractionReasons } from "./primitives/interaction";
import { uiFloatingAlignments, uiFloatingSides } from "./primitives/positioning";
import {
  uiContrastModes,
  uiControlPresentationModes,
  uiDensityModes,
  uiEmphasisModes,
  uiInteractionStates,
  uiMaterialModes,
  uiPlacementModes,
  uiSelectionStates,
  uiSemanticTokenNames,
  uiShapeModes,
  uiThemeModes,
  uiToneModes,
} from "./tokens/value";

export const uiContractGroups = {
  components: {
    backupCollapsibleBlock: "@mk-combos/ui/components/backup-collapsible-block",
    breadcrumbs: "@mk-combos/ui/components/breadcrumbs",
    controllerHintStrip: "@mk-combos/ui/components/controller-hint-strip",
    controllerAccessGate: "@mk-combos/ui/components/controller-access-gate",
    displayModeSwitcher: "@mk-combos/ui/components/display-mode-switcher",
    exportDialog: "@mk-combos/ui/components/export-dialog",
    firstLaunchSetupForm: "@mk-combos/ui/components/first-launch-setup-form",
    gameSwitcher: "@mk-combos/ui/components/game-switcher",
    globalTopBar: "@mk-combos/ui/components/global-top-bar",
    importPreviewDialog: "@mk-combos/ui/components/import-preview-dialog",
    languageSwitcher: "@mk-combos/ui/components/language-switcher",
    notationLegendTable: "@mk-combos/ui/components/notation-legend-table",
    runtime: "@mk-combos/ui/components/runtime",
    schema: "@mk-combos/ui/components/schema",
    topBarDropdownMenu: "@mk-combos/ui/components/top-bar-dropdown-menu",
    type: "@mk-combos/ui/components/type",
    value: "@mk-combos/ui/components/value",
  },
  focusNavigation: {
    runtime: "@mk-combos/ui/focus-navigation/runtime",
    schema: "@mk-combos/ui/focus-navigation/schema",
    type: "@mk-combos/ui/focus-navigation/type",
    value: "@mk-combos/ui/focus-navigation/value",
  },
  hooks: {
    fieldMessage: "@mk-combos/ui/hooks/field-message",
    focusNavigation: "@mk-combos/ui/hooks/focus-navigation",
    intents: "@mk-combos/ui/hooks/intents",
    openState: "@mk-combos/ui/hooks/open-state",
    responsiveMode: "@mk-combos/ui/hooks/responsive-mode",
  },
  icons: {
    alertTriangle: "@mk-combos/ui/icons/alert-triangle",
    check: "@mk-combos/ui/icons/check",
    chevronDown: "@mk-combos/ui/icons/chevron-down",
    chevronLeft: "@mk-combos/ui/icons/chevron-left",
    chevronRight: "@mk-combos/ui/icons/chevron-right",
    chevronUp: "@mk-combos/ui/icons/chevron-up",
    circleHelp: "@mk-combos/ui/icons/circle-help",
    download: "@mk-combos/ui/icons/download",
    edit: "@mk-combos/ui/icons/edit",
    gamepad2: "@mk-combos/ui/icons/gamepad-2",
    menu: "@mk-combos/ui/icons/menu",
    plus: "@mk-combos/ui/icons/plus",
    search: "@mk-combos/ui/icons/search",
    settings: "@mk-combos/ui/icons/settings",
    trash2: "@mk-combos/ui/icons/trash-2",
    upload: "@mk-combos/ui/icons/upload",
    x: "@mk-combos/ui/icons/x",
  },
  notation: {
    runtime: "@mk-combos/ui/notation/runtime",
    schema: "@mk-combos/ui/notation/schema",
    type: "@mk-combos/ui/notation/type",
    value: "@mk-combos/ui/notation/value",
  },
  primitives: {
    button: "@mk-combos/ui/primitives/button",
    dialog: "@mk-combos/ui/primitives/dialog",
    drawer: "@mk-combos/ui/primitives/drawer",
    disclosure: "@mk-combos/ui/primitives/disclosure",
    field: "@mk-combos/ui/primitives/field",
    focus: "@mk-combos/ui/primitives/focus",
    interaction: "@mk-combos/ui/primitives/interaction",
    layout: "@mk-combos/ui/primitives/layout",
    menu: "@mk-combos/ui/primitives/menu",
    popover: "@mk-combos/ui/primitives/popover",
    positioning: "@mk-combos/ui/primitives/positioning",
    segmentedControl: "@mk-combos/ui/primitives/segmented-control",
    state: "@mk-combos/ui/primitives/state",
  },
  styles: {
    css: "@mk-combos/ui/styles.css",
  },
  tokens: {
    schema: "@mk-combos/ui/tokens/schema",
    type: "@mk-combos/ui/tokens/type",
    value: "@mk-combos/ui/tokens/value",
  },
} as const;

export const mkCombosUi = {
  packageName: "@mk-combos/ui",
  groups: uiContractGroups,
  valueSets: {
    backupDisclosureStates,
    backupOperationStates,
    backupPersistenceModes,
    backupSliceStatuses,
    backupValidationMessageTones,
    backupValidationStatuses,
    componentInteractionReasons,
    componentOptionStatuses,
    controllerAccessStates,
    notationDisplayModes,
    uiContrastModes,
    uiControlPresentationModes,
    uiDensityModes,
    uiEmphasisModes,
    uiInteractionStates,
    uiMaterialModes,
    uiNotationIconKinds,
    uiNotationTokens,
    uiNotationTokenStates,
    uiPlacementModes,
    uiSelectionStates,
    uiSemanticTokenNames,
    uiShapeModes,
    uiThemeModes,
    uiToneModes,
    uiFocusDirections,
    uiFloatingAlignments,
    uiFloatingSides,
    uiPrimitiveInteractionReasons,
    uiResponsiveModes,
  },
} as const;
