import type { LanguageCode } from "@mk-combos/contracts/settings/type";
import { languageCodes } from "@mk-combos/contracts/settings/value";

import type { AppCopy } from "./type";

export const appCopyByLanguage = {
  [languageCodes.EN]: {
    backup: {
      cancel: "Cancel",
      chooseAnotherFile: "Choose another file",
      confirmExport: "Download file",
      confirmReplace: "Replace {game} data",
      exportDescription:
        "Download this game's local data as a file. Nothing in the browser will change.",
      exportFailure: "We couldn't create this backup. Try again.",
      exportedAtLabel: "Created",
      exportLabel: "Create backup",
      exportSessionOnly:
        "This backup includes changes from the current session. Download it now if you don't want to lose them.",
      exportTitle: "Create a {game} backup",
      importComplete: "{game} data restored.",
      importDescription: "Review the file before replacing the {game} data stored in this browser.",
      importFailure: "We couldn't restore this backup. Try again.",
      importLabel: "Restore from backup",
      importTitle: "Restore {game} from this backup?",
      invalidFile: "This isn't a valid MK Combos backup. Choose another file.",
      invalidSlice: "This backup contains damaged or unsupported game data.",
      mismatchedGame: "This backup is for another game. Choose a {game} backup.",
      operationBlocked: "Finish or cancel the current backup action first.",
      replaceImpact:
        "This will replace custom combos, lists, and the last catalog selection for {game}. Other games and interface settings won't change.",
      reviewWarning: "Some saved combos or lists may need review after restore.",
      sessionOnly:
        "Data restored for now, but it wasn't saved. Create a backup before reloading the page.",
      sliceReady: "Ready to create a backup.",
      sliceSummary: "This backup contains data for one game.",
      unsupportedVersion: "This backup format isn't supported by this version of MK Combos.",
    },
    catalog: {
      activeFiltersLabel: "Active filters",
      applyFilters: "Apply filters",
      availableOptions: "{count} available",
      backToCharacter: "Back to fighters",
      characterLabel: "Fighter",
      chooseCharacterDescription: "Choose a fighter to see their available team or variation.",
      chooseCharacterTitle: "Choose a fighter",
      chooseContextDescription: "Complete the matchup to load its combos.",
      chooseContextTitle: "Choose a variation or kameo",
      changeContext: "Open to change the fighter or game context.",
      clearCharacter: "Clear fighter",
      clearContext: "Clear selection",
      clearFilters: "Clear filters",
      comboCount: "Combos: {count}",
      combosLabel: "Combos",
      damageLabel: "Damage",
      description: "Choose a fighter and variation or kameo. Filters narrow the list immediately.",
      discardFilterChanges: "Discard changes",
      difficultyLabel: "Difficulty",
      emptyFilterOptions: "No options are available for {filter} with the current selection.",
      filterChipLabels: {
        difficulty: {
          easy: "Easy",
          hard: "Hard",
          medium: "Medium",
        },
        interactable: {
          "corner-attack": "Corner attack",
          "position-escape": "Position escape",
        },
        position: {
          antiAir: "Anti-air",
          corner: "In the corner",
          midscreen: "Center",
        },
        routeClass: {
          bnb: "Basic",
          kameo: "With Kameo",
          metered: "With meter",
          punish: "Punish",
          stage: "With a stage object",
        },
        source: {
          community: "From players",
          curated: "From editors",
          personal: "Mine",
        },
      },
      filterChipMeterLabels: {
        few: "{count} bars",
        many: "{count} bars",
        one: "{count} bar",
        other: "{count} bars",
        zero: "No meter",
      },
      filterLabels: {
        difficulty: "Difficulty",
        interactable: "Interactables",
        meter: "Meter",
        position: "Position",
        routeClass: "Route class",
        source: "Source",
        stage: "Arena",
      },
      filtersLabel: "Filters",
      fighterRosterLabel: "Fighter roster",
      gameContextByKind: {
        kameo: "Kameo",
        variation: "Variation",
      },
      meterLabel: "Meter",
      loadingFilters: "Updating filters",
      noCombosDescription: "There are no published combos for this selection yet.",
      noCombosTitle: "No combos yet",
      noFilterResultsDescription: "No combos match these filters. Clear one or more filters.",
      noFilterResultsTitle: "No matching combos",
      noOptionData: "No combo data",
      navigateCommand: "Navigate",
      positionLabel: "Position",
      persistenceWarning: "Catalog changes are active for this session but could not be saved.",
      recoveryWarning: "Some catalog options were adjusted because the link was out of date.",
      resetFilters: "Reset filters",
      restoreWarning:
        "The last catalog selection could not be restored. Choose a fighter to continue.",
      removeFilter: "Remove filter “{filter}”",
      resultCount: "{count} found",
      routeTypeLabel: "Route",
      selectContextForCharacter: "Selected fighter: {character}",
      selectCommand: "Select",
      sourceLabel: "Source",
      title: "Catalog",
      valueLabels: {
        antiAir: "Anti-air",
        bnb: "Bread and butter",
        corner: "Corner",
        easy: "Easy",
        hard: "Hard",
        kameo: "Kameo route",
        medium: "Medium",
        metered: "Metered",
        midscreen: "Midscreen",
        punish: "Punish",
        community: "Community",
        curated: "Curated",
        personal: "Personal",
        stage: "Stage route",
      },
      viewCombo: "View combo",
    },
    comboDetail: {
      backToCatalog: "Back to catalog",
      characterLabel: "Fighter",
      comboUnavailableDescription: "This combo could not be found in the current game data.",
      comboUnavailableTitle: "Combo unavailable",
      customSource: "Custom combo",
      damageLabel: "Damage",
      description: "Inputs, route notes, and verified metadata in one readable view.",
      difficultyLabel: "Difficulty",
      frameDataDescription: "A frame-by-frame timeline is unavailable for this combo.",
      frameDataTitle: "Frame data",
      frame: {
        closeDetails: "Close frame details",
        details: "Frame details",
        focusMatchingWhiteboardStep: "Focus the matching combo step",
        lifecyclePending: "Reviewing a changed route",
        lifecycleReady: "Frame view ready",
        lifecycleRepair: "Reviewing a route that needs repair",
        lifecycleSaving: "Saving frame information",
        scope: "Frame-data scope",
        selectedMove: "Selected move",
        summaryLabel: "Frame summary",
        timelineLabel: "Frame timeline",
        unavailableLabel: "Frame values unavailable",
        wholeCombo: "Whole combo",
      },
      gameVersionLabel: "Game version",
      howToTitle: "How to perform it",
      interactablesLabel: "Interactables",
      kameoLabel: "Kameo",
      loadErrorDescription:
        "The saved data for this combo is invalid or unsupported. Return to the catalog and restore a valid backup.",
      loadErrorTitle: "Combo could not be loaded",
      metadataTitle: "Combo details",
      meterLabel: "Meter",
      moveCountLabel: "Moves",
      notesTitle: "Notes",
      positionLabel: "Position",
      routeTypeLabel: "Route",
      seededSource: "Game catalog",
      sourceLabel: "Source",
      stageLabel: "Stage",
      stateInvalid: "This saved route is no longer valid against the current game data.",
      stateInvalidLabel: "Invalid route",
      stateStale: "This saved route changed after a game-data update. Review the marked step.",
      stateStaleLabel: "Route needs review",
      starterLabel: "Starter",
      tagLabels: {
        beginner: "Beginner",
        community: "Community",
        corner: "Corner",
        definitive: "Definitive",
        metered: "Metered",
        optimal: "Optimal",
        "pair-coverage": "Pair coverage",
        practice: "Practice",
        stage: "Stage",
        starter: "Starter",
      },
      tagsLabel: "Tags",
      title: "Combo detail",
      variationLabel: "Variation",
      validPrefix: "Valid moves before the break: {count}",
      whiteboard: {
        afterTarget: "After",
        appendTarget: "Add a move",
        beforeTarget: "Before",
        board: "Combo route",
        cancelPickUp: "Cancel move selection",
        candidates: "Available moves",
        closeMenu: "Close menu",
        closePicker: "Close move picker",
        comboEnd: "End of combo",
        comboStart: "Start of combo",
        continuationFromPreviousRow: "Continued from the previous row",
        continuationToNextRow: "Continues on the next row",
        contextSummary: "Combo context",
        emptyPath: "No moves in this combo",
        groups: "Move groups",
        hints: ["Read the route from left to right."],
        insertTarget: "Insert move",
        invalidBoundary: "Route breaks here",
        linkLabel: "Link",
        loadingCandidates: "Loading moves",
        menu: "Combo step menu",
        nextGroup: "Next move group",
        noCandidates: "No available moves",
        picker: "Move picker",
        previousGroup: "Previous move group",
        reorderTarget: "Move position",
        replaceTarget: "Replace move",
        runtimeSummary: "Route summary",
        saving: "Saving combo",
        stepLabel: "Step {index}",
        useAppendTarget: "Add at the end",
      },
    },
    firstLaunch: {
      capabilities: [
        "Find the right combo faster in game catalogs.",
        "Save combos to lists and build your own.",
        "Use a gamepad and keep a separate backup for each game.",
      ],
      capabilitiesIntro: "With MK Combos, you can:",
      confirm: "Open catalog",
      confirmDisabled: "This game is unavailable. Choose another.",
      dataNotice: "Your lists and custom combos stay in this browser unless you create a backup.",
      description:
        "Choose a starting game, interface language, and button labels. You can change them later.",
      displayModeLabel: "Button labels",
      formTitle: "Your preferences",
      gameLabel: "Starting game",
      languageLabel: "Interface language",
      legendCaption: "Preview",
      legendMarkersHeader: "Buttons",
      legendModeHeader: "Format",
      sessionOnly:
        "This browser can't save your choices. They will be lost after you reload or close the page.",
      sessionOnlyAcknowledge: "Continue without saving",
      submissionError: "We couldn't apply these settings. Try again.",
      title: "Set up MK Combos",
    },
    settings: {
      autosave: "Changes save automatically.",
      backupDescription:
        "Each backup contains data for one game. Interface settings and other games aren't included.",
      backupTab: "Game backups",
      close: "Close settings",
      description: "Adjust the interface or manage a separate backup for each game.",
      displayModeLabel: "Button labels",
      interfaceDescription: "Choose the theme, interface language, and how combo inputs appear.",
      interfaceTab: "Interface",
      languageLabel: "Interface language",
      legendCaption: "Button label reference",
      legendMarkersHeader: "Buttons",
      legendModeHeader: "Format",
      persistenceError: "We couldn't apply this change. Try again.",
      sectionsLabel: "Settings sections",
      sessionOnly:
        "Changes are active, but this browser can't save them. They'll be lost after reload or closing the page.",
      themeDark: "Dark",
      themeLabel: "Theme",
      themeLight: "Light",
      themeSystem: "System",
      title: "Settings",
    },
    shell: {
      breadcrumbs: "Breadcrumbs",
      builder: "Builder",
      catalog: "Catalog",
      chooseGame: "Choose game",
      closeNavigation: "Close navigation",
      firstLaunch: "First launch",
      namedLists: "Named Lists",
      navigation: "Navigation",
      openCatalog: "Open {game} Catalog",
      openGlobalMenu: "Open global menu",
      routeUnavailableDescription:
        "The requested route does not match an installed game or supported application surface.",
      routeUnavailableTitle: "This route is unavailable",
      settings: "Settings",
      unavailableRoute: "Unavailable route",
    },
  },
  [languageCodes.UA]: {
    backup: {
      cancel: "Скасувати",
      chooseAnotherFile: "Вибрати інший файл",
      confirmExport: "Завантажити файл",
      confirmReplace: "Замінити дані {game}",
      exportDescription: "Завантажте локальні дані цієї гри у файл. Дані в браузері не зміняться.",
      exportFailure: "Не вдалося створити резервну копію. Спробуйте ще раз.",
      exportedAtLabel: "Створено",
      exportLabel: "Створити копію",
      exportSessionOnly:
        "Копія міститиме зміни з поточної сесії. Завантажте її зараз, щоб не втратити ці зміни.",
      exportTitle: "Створити резервну копію {game}",
      importComplete: "Дані {game} відновлено.",
      importDescription: "Перевірте файл перед заміною даних {game}, збережених у цьому браузері.",
      importFailure: "Не вдалося відновити дані з копії. Спробуйте ще раз.",
      importLabel: "Відновити з копії",
      importTitle: "Відновити {game} із цієї резервної копії?",
      invalidFile: "Це не резервна копія MK Combos. Виберіть інший файл.",
      invalidSlice: "Ця копія містить пошкоджені або непідтримувані дані гри.",
      mismatchedGame: "Це копія для іншої гри. Виберіть копію {game}.",
      operationBlocked: "Спочатку завершіть або скасуйте поточну дію з резервною копією.",
      replaceImpact:
        "Поточні власні комбо, списки й останній вибір у каталозі {game} буде замінено даними з файла. Дані інших ігор і налаштування інтерфейсу не зміняться.",
      reviewWarning: "Після відновлення деякі комбо або списки можуть потребувати перевірки.",
      sessionOnly:
        "Дані відновлено лише тимчасово. Створіть резервну копію перед перезавантаженням сторінки.",
      sliceReady: "Готово до створення копії.",
      sliceSummary: "Ця копія містить дані лише однієї гри.",
      unsupportedVersion: "Ця версія MK Combos не підтримує формат вибраної копії.",
    },
    catalog: {
      activeFiltersLabel: "Активні фільтри",
      applyFilters: "Застосувати фільтри",
      availableOptions: "Доступно: {count}",
      backToCharacter: "Назад до бійців",
      characterLabel: "Боєць",
      chooseCharacterDescription: "Оберіть бійця, щоб побачити доступну команду або варіацію.",
      chooseCharacterTitle: "Оберіть бійця",
      chooseContextDescription: "Завершіть вибір, щоб завантажити комбо.",
      chooseContextTitle: "Оберіть варіацію або камео",
      changeContext: "Відкрийте, щоб змінити бійця або контекст гри.",
      clearCharacter: "Очистити бійця",
      clearContext: "Очистити вибір",
      clearFilters: "Очистити фільтри",
      comboCount: "Комбо: {count}",
      combosLabel: "Комбо",
      damageLabel: "Шкода",
      description: "Оберіть бійця й варіацію або камео. Фільтри одразу звузять список.",
      discardFilterChanges: "Скасувати зміни",
      difficultyLabel: "Складність",
      emptyFilterOptions: "Для поточного вибору немає доступних опцій «{filter}».",
      filterChipLabels: {
        difficulty: {
          easy: "Легке",
          hard: "Складне",
          medium: "Середнє",
        },
        interactable: {
          "corner-attack": "Атака в куті",
          "position-escape": "Зміна позиції",
        },
        position: {
          antiAir: "Проти стрибка",
          corner: "У куті",
          midscreen: "По центру",
        },
        routeClass: {
          bnb: "Базове",
          kameo: "З камео",
          metered: "Зі шкалою",
          punish: "Покарання",
          stage: "З об’єктом арени",
        },
        source: {
          community: "Від гравців",
          curated: "Від редакції",
          personal: "Мої",
        },
      },
      filterChipMeterLabels: {
        few: "{count} поділки",
        many: "{count} поділок",
        one: "{count} поділка",
        other: "{count} поділки",
        zero: "Без шкали",
      },
      filterLabels: {
        difficulty: "Складність",
        interactable: "Об’єкти арени",
        meter: "Шкала",
        position: "Позиція",
        routeClass: "Клас маршруту",
        source: "Джерело",
        stage: "Арена",
      },
      filtersLabel: "Фільтри",
      fighterRosterLabel: "Склад бійців",
      gameContextByKind: {
        kameo: "Камео",
        variation: "Варіація",
      },
      meterLabel: "Шкала",
      loadingFilters: "Оновлення фільтрів",
      noCombosDescription: "Для цього вибору ще немає опублікованих комбо.",
      noCombosTitle: "Комбо ще немає",
      noFilterResultsDescription:
        "За цими фільтрами комбо немає. Очистьте один або кілька фільтрів.",
      noFilterResultsTitle: "Нічого не знайдено",
      noOptionData: "Немає даних про комбо",
      navigateCommand: "Навігація",
      positionLabel: "Позиція",
      persistenceWarning: "Зміни каталогу діють у цій сесії, але їх не вдалося зберегти.",
      recoveryWarning: "Деякі параметри каталогу змінено, бо посилання застаріло.",
      resetFilters: "Скинути фільтри",
      restoreWarning:
        "Не вдалося відновити останній вибір каталогу. Оберіть бійця, щоб продовжити.",
      removeFilter: "Прибрати фільтр «{filter}»",
      resultCount: "Знайдено: {count}",
      routeTypeLabel: "Маршрут",
      selectContextForCharacter: "Обраний боєць: {character}",
      selectCommand: "Вибір",
      sourceLabel: "Джерело",
      title: "Каталог",
      valueLabels: {
        antiAir: "Проти стрибка",
        bnb: "Базове комбо",
        corner: "Кут",
        easy: "Легко",
        hard: "Складно",
        kameo: "Маршрут із камео",
        medium: "Середньо",
        metered: "Зі шкалою",
        midscreen: "Центр арени",
        punish: "Покарання",
        community: "Спільнота",
        curated: "Редакційні",
        personal: "Особисті",
        stage: "Маршрут арени",
      },
      viewCombo: "Відкрити комбо",
    },
    comboDetail: {
      backToCatalog: "Назад до каталогу",
      characterLabel: "Боєць",
      comboUnavailableDescription: "Не вдалося знайти це комбо в актуальних даних гри.",
      comboUnavailableTitle: "Комбо недоступне",
      customSource: "Власне комбо",
      damageLabel: "Шкода",
      description: "Команди, примітки до маршруту й перевірена метаінформація в одному місці.",
      difficultyLabel: "Складність",
      frameDataDescription: "Для цього комбо покадрова шкала недоступна.",
      frameDataTitle: "Дані кадрів",
      frame: {
        closeDetails: "Закрити дані кадрів",
        details: "Деталі кадрів",
        focusMatchingWhiteboardStep: "Перейти до відповідного кроку комбо",
        lifecyclePending: "Перевірка зміненого маршруту",
        lifecycleReady: "Перегляд кадрів готовий",
        lifecycleRepair: "Перевірка маршруту, який потребує виправлення",
        lifecycleSaving: "Збереження даних кадрів",
        scope: "Обсяг даних кадрів",
        selectedMove: "Обраний рух",
        summaryLabel: "Зведення кадрів",
        timelineLabel: "Шкала кадрів",
        unavailableLabel: "Значення кадрів недоступні",
        wholeCombo: "Усе комбо",
      },
      gameVersionLabel: "Версія гри",
      howToTitle: "Як виконати",
      interactablesLabel: "Об’єкти арени",
      kameoLabel: "Камео",
      loadErrorDescription:
        "Збережені дані цього комбо пошкоджені або не підтримуються. Поверніться до каталогу та відновіть коректну резервну копію.",
      loadErrorTitle: "Не вдалося завантажити комбо",
      metadataTitle: "Характеристики комбо",
      meterLabel: "Шкала",
      moveCountLabel: "Рухів",
      notesTitle: "Примітки",
      positionLabel: "Позиція",
      routeTypeLabel: "Маршрут",
      seededSource: "Каталог гри",
      sourceLabel: "Джерело",
      stageLabel: "Арена",
      stateInvalid: "Цей збережений маршрут більше не відповідає актуальним даним гри.",
      stateInvalidLabel: "Некоректний маршрут",
      stateStale: "Маршрут змінився після оновлення даних гри. Перевірте позначений крок.",
      stateStaleLabel: "Маршрут потребує перевірки",
      starterLabel: "Початок",
      tagLabels: {
        beginner: "Для початківців",
        community: "Від спільноти",
        corner: "Кут",
        definitive: "Основне",
        metered: "Зі шкалою",
        optimal: "Оптимальне",
        "pair-coverage": "Для цієї пари",
        practice: "Для тренування",
        stage: "Арена",
        starter: "Початок",
      },
      tagsLabel: "Теги",
      title: "Комбо",
      variationLabel: "Варіація",
      validPrefix: "Коректних рухів до помилки: {count}",
      whiteboard: {
        afterTarget: "Після",
        appendTarget: "Додати рух",
        beforeTarget: "Перед",
        board: "Маршрут комбо",
        cancelPickUp: "Скасувати вибір руху",
        candidates: "Доступні рухи",
        closeMenu: "Закрити меню",
        closePicker: "Закрити вибір руху",
        comboEnd: "Кінець комбо",
        comboStart: "Початок комбо",
        continuationFromPreviousRow: "Продовження з попереднього рядка",
        continuationToNextRow: "Продовження в наступному рядку",
        contextSummary: "Контекст комбо",
        emptyPath: "У цьому комбо немає рухів",
        groups: "Групи рухів",
        hints: ["Читайте маршрут зліва направо."],
        insertTarget: "Вставити рух",
        invalidBoundary: "Тут маршрут переривається",
        linkLabel: "Зв’язка",
        loadingCandidates: "Завантаження рухів",
        menu: "Меню кроку комбо",
        nextGroup: "Наступна група рухів",
        noCandidates: "Немає доступних рухів",
        picker: "Вибір руху",
        previousGroup: "Попередня група рухів",
        reorderTarget: "Позиція руху",
        replaceTarget: "Замінити рух",
        runtimeSummary: "Зведення маршруту",
        saving: "Збереження комбо",
        stepLabel: "Крок {index}",
        useAppendTarget: "Додати в кінці",
      },
    },
    firstLaunch: {
      capabilities: [
        "Швидко знаходьте потрібні комбо в каталогах ігор.",
        "Зберігайте комбо у списки та створюйте власні.",
        "Керуйте застосунком із геймпада та створюйте окрему копію для кожної гри.",
      ],
      capabilitiesIntro: "З MK Combos ви можете:",
      confirm: "Відкрити каталог",
      confirmDisabled: "Ця гра недоступна. Оберіть іншу.",
      dataNotice:
        "Ваші списки й власні комбо зберігаються лише в цьому браузері, доки ви не створите резервну копію.",
      description:
        "Оберіть початкову гру, мову інтерфейсу та зручні позначення кнопок. Усе це можна змінити пізніше.",
      displayModeLabel: "Позначення кнопок",
      formTitle: "Ваші налаштування",
      gameLabel: "Початкова гра",
      languageLabel: "Мова інтерфейсу",
      legendCaption: "Приклад",
      legendMarkersHeader: "Кнопки",
      legendModeHeader: "Формат",
      sessionOnly:
        "Браузер не може зберегти ці налаштування. Вони зникнуть після перезавантаження або закриття сторінки.",
      sessionOnlyAcknowledge: "Продовжити без збереження",
      submissionError: "Не вдалося застосувати налаштування. Спробуйте ще раз.",
      title: "Налаштуймо MK Combos",
    },
    settings: {
      autosave: "Зміни зберігаються автоматично.",
      backupDescription:
        "Кожна копія містить дані лише однієї гри. Налаштування інтерфейсу й дані інших ігор до неї не входять.",
      backupTab: "Резервні копії",
      close: "Закрити налаштування",
      description: "Налаштуйте інтерфейс або керуйте окремими резервними копіями ігор.",
      displayModeLabel: "Позначення кнопок",
      interfaceDescription: "Оберіть тему, мову інтерфейсу та спосіб відображення кнопок у комбо.",
      interfaceTab: "Інтерфейс",
      languageLabel: "Мова інтерфейсу",
      legendCaption: "Довідка з позначень кнопок",
      legendMarkersHeader: "Кнопки",
      legendModeHeader: "Формат",
      persistenceError: "Не вдалося застосувати зміну. Спробуйте ще раз.",
      sectionsLabel: "Розділи налаштувань",
      sessionOnly:
        "Зміни вже діють, але браузер не може їх зберегти. Вони зникнуть після перезавантаження або закриття сторінки.",
      themeDark: "Темна",
      themeLabel: "Тема",
      themeLight: "Світла",
      themeSystem: "Системна",
      title: "Налаштування",
    },
    shell: {
      breadcrumbs: "Навігаційний шлях",
      builder: "Конструктор",
      catalog: "Каталог",
      chooseGame: "Обрати гру",
      closeNavigation: "Закрити навігацію",
      firstLaunch: "Перший запуск",
      namedLists: "Іменовані списки",
      navigation: "Навігація",
      openCatalog: "Відкрити каталог {game}",
      openGlobalMenu: "Відкрити глобальне меню",
      routeUnavailableDescription:
        "Запитаний маршрут не відповідає встановленій грі або підтримуваному розділу застосунку.",
      routeUnavailableTitle: "Цей маршрут недоступний",
      settings: "Налаштування",
      unavailableRoute: "Недоступний маршрут",
    },
  },
} as const satisfies Record<LanguageCode, AppCopy>;
