import type { LanguageCode } from "@mk-combos/contracts/settings/type";
import { languageCodes } from "@mk-combos/contracts/settings/value";

import type { AppCopy } from "./type";

export const appCopyByLanguage = {
  [languageCodes.EN]: {
    backup: {
      cancel: "Cancel",
      chooseAnotherFile: "Choose another file",
      confirmExport: "Download file",
      confirmReplace: "Replace {game} data",
      exportDescription:
        "Download this game's local data as a file. Nothing in the browser will change.",
      exportFailure: "We couldn't create this backup. Try again.",
      exportedAtLabel: "Created",
      exportLabel: "Create backup",
      exportSessionOnly:
        "This backup includes changes from the current session. Download it now if you don't want to lose them.",
      exportTitle: "Create a {game} backup",
      importComplete: "{game} data restored.",
      importDescription: "Review the file before replacing the {game} data stored in this browser.",
      importFailure: "We couldn't restore this backup. Try again.",
      importLabel: "Restore from backup",
      importTitle: "Restore {game} from this backup?",
      invalidFile: "This isn't a valid MK Combos backup. Choose another file.",
      invalidSlice: "This backup contains damaged or unsupported game data.",
      mismatchedGame: "This backup is for another game. Choose a {game} backup.",
      operationBlocked: "Finish or cancel the current backup action first.",
      replaceImpact:
        "This will replace custom combos, lists, and the last catalog selection for {game}. Other games and interface settings won't change.",
      reviewWarning: "Some saved combos or lists may need review after restore.",
      sessionOnly:
        "Data restored for now, but it wasn't saved. Create a backup before reloading the page.",
      sliceReady: "Ready to create a backup.",
      sliceSummary: "This backup contains data for one game.",
      unsupportedVersion: "This backup format isn't supported by this version of MK Combos.",
    },
    firstLaunch: {
      capabilities: [
        "Find the right combo faster in game catalogs.",
        "Save combos to lists and build your own.",
        "Use a gamepad and keep a separate backup for each game.",
      ],
      capabilitiesIntro: "With MK Combos, you can:",
      confirm: "Open catalog",
      confirmDisabled: "This game is unavailable. Choose another.",
      dataNotice: "Your lists and custom combos stay in this browser unless you create a backup.",
      description:
        "Choose a starting game, interface language, and button labels. You can change them later.",
      displayModeLabel: "Button labels",
      formTitle: "Your preferences",
      gameLabel: "Starting game",
      languageLabel: "Interface language",
      legendCaption: "Preview",
      legendMarkersHeader: "Buttons",
      legendModeHeader: "Format",
      sessionOnly:
        "This browser can't save your choices. They will be lost after you reload or close the page.",
      sessionOnlyAcknowledge: "Continue without saving",
      submissionError: "We couldn't apply these settings. Try again.",
      title: "Set up MK Combos",
    },
    settings: {
      autosave: "Changes save automatically.",
      backupDescription:
        "Each backup contains data for one game. Interface settings and other games aren't included.",
      backupTab: "Game backups",
      description: "Adjust the interface or manage a separate backup for each game.",
      displayModeLabel: "Button labels",
      interfaceDescription: "Choose the interface language and how combo inputs appear.",
      interfaceTab: "Interface",
      languageLabel: "Interface language",
      legendCaption: "Button label reference",
      legendMarkersHeader: "Buttons",
      legendModeHeader: "Format",
      persistenceError: "We couldn't apply this change. Try again.",
      returnBuilder: "Back to {game} builder",
      returnCatalog: "Back to {game} catalog",
      returnCombo: "Back to {game} combo",
      returnLists: "Back to {game} lists",
      sectionsLabel: "Settings sections",
      sessionOnly:
        "Changes are active, but this browser can't save them. They'll be lost after reload or closing the page.",
      title: "Settings",
    },
    shell: {
      breadcrumbs: "Breadcrumbs",
      builder: "Builder",
      catalog: "Catalog",
      chooseGame: "Choose game",
      closeNavigation: "Close navigation",
      firstLaunch: "First launch",
      namedLists: "Named Lists",
      navigation: "Navigation",
      openGlobalMenu: "Open global menu",
      settings: "Settings",
      unavailableRoute: "Unavailable route",
    },
  },
  [languageCodes.UA]: {
    backup: {
      cancel: "Скасувати",
      chooseAnotherFile: "Вибрати інший файл",
      confirmExport: "Завантажити файл",
      confirmReplace: "Замінити дані {game}",
      exportDescription: "Завантажте локальні дані цієї гри у файл. Дані в браузері не зміняться.",
      exportFailure: "Не вдалося створити резервну копію. Спробуйте ще раз.",
      exportedAtLabel: "Створено",
      exportLabel: "Створити копію",
      exportSessionOnly:
        "Копія міститиме зміни з поточної сесії. Завантажте її зараз, щоб не втратити ці зміни.",
      exportTitle: "Створити резервну копію {game}",
      importComplete: "Дані {game} відновлено.",
      importDescription: "Перевірте файл перед заміною даних {game}, збережених у цьому браузері.",
      importFailure: "Не вдалося відновити дані з копії. Спробуйте ще раз.",
      importLabel: "Відновити з копії",
      importTitle: "Відновити {game} із цієї резервної копії?",
      invalidFile: "Це не резервна копія MK Combos. Виберіть інший файл.",
      invalidSlice: "Ця копія містить пошкоджені або непідтримувані дані гри.",
      mismatchedGame: "Це копія для іншої гри. Виберіть копію {game}.",
      operationBlocked: "Спочатку завершіть або скасуйте поточну дію з резервною копією.",
      replaceImpact:
        "Поточні власні комбо, списки й останній вибір у каталозі {game} буде замінено даними з файла. Дані інших ігор і налаштування інтерфейсу не зміняться.",
      reviewWarning: "Після відновлення деякі комбо або списки можуть потребувати перевірки.",
      sessionOnly:
        "Дані відновлено лише тимчасово. Створіть резервну копію перед перезавантаженням сторінки.",
      sliceReady: "Готово до створення копії.",
      sliceSummary: "Ця копія містить дані лише однієї гри.",
      unsupportedVersion: "Ця версія MK Combos не підтримує формат вибраної копії.",
    },
    firstLaunch: {
      capabilities: [
        "Швидко знаходьте потрібні комбо в каталогах ігор.",
        "Зберігайте комбо у списки та створюйте власні.",
        "Керуйте застосунком із геймпада та створюйте окрему копію для кожної гри.",
      ],
      capabilitiesIntro: "З MK Combos ви можете:",
      confirm: "Відкрити каталог",
      confirmDisabled: "Ця гра недоступна. Оберіть іншу.",
      dataNotice:
        "Ваші списки й власні комбо зберігаються лише в цьому браузері, доки ви не створите резервну копію.",
      description:
        "Оберіть початкову гру, мову інтерфейсу та зручні позначення кнопок. Усе це можна змінити пізніше.",
      displayModeLabel: "Позначення кнопок",
      formTitle: "Ваші налаштування",
      gameLabel: "Початкова гра",
      languageLabel: "Мова інтерфейсу",
      legendCaption: "Приклад",
      legendMarkersHeader: "Кнопки",
      legendModeHeader: "Формат",
      sessionOnly:
        "Браузер не може зберегти ці налаштування. Вони зникнуть після перезавантаження або закриття сторінки.",
      sessionOnlyAcknowledge: "Продовжити без збереження",
      submissionError: "Не вдалося застосувати налаштування. Спробуйте ще раз.",
      title: "Налаштуймо MK Combos",
    },
    settings: {
      autosave: "Зміни зберігаються автоматично.",
      backupDescription:
        "Кожна копія містить дані лише однієї гри. Налаштування інтерфейсу й дані інших ігор до неї не входять.",
      backupTab: "Резервні копії",
      description: "Налаштуйте інтерфейс або керуйте окремими резервними копіями ігор.",
      displayModeLabel: "Позначення кнопок",
      interfaceDescription: "Оберіть мову інтерфейсу та спосіб відображення кнопок у комбо.",
      interfaceTab: "Інтерфейс",
      languageLabel: "Мова інтерфейсу",
      legendCaption: "Довідка з позначень кнопок",
      legendMarkersHeader: "Кнопки",
      legendModeHeader: "Формат",
      persistenceError: "Не вдалося застосувати зміну. Спробуйте ще раз.",
      returnBuilder: "Назад до конструктора {game}",
      returnCatalog: "Назад до каталогу {game}",
      returnCombo: "Назад до комбо {game}",
      returnLists: "Назад до списків {game}",
      sectionsLabel: "Розділи налаштувань",
      sessionOnly:
        "Зміни вже діють, але браузер не може їх зберегти. Вони зникнуть після перезавантаження або закриття сторінки.",
      title: "Налаштування",
    },
    shell: {
      breadcrumbs: "Навігаційний шлях",
      builder: "Конструктор",
      catalog: "Каталог",
      chooseGame: "Обрати гру",
      closeNavigation: "Закрити навігацію",
      firstLaunch: "Перший запуск",
      namedLists: "Іменовані списки",
      navigation: "Навігація",
      openGlobalMenu: "Відкрити глобальне меню",
      settings: "Налаштування",
      unavailableRoute: "Недоступний маршрут",
    },
  },
} as const satisfies Record<LanguageCode, AppCopy>;
